### ISSUE TITLE
Remove the standalone `-f` flag

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#100]
Offline discussions with @hausdorff:

The current version of `ksonnet.next` is structured heavily around the ksonnet application directory structure and the concept of environments. Should we continue to support the `show`, `apply`, `delete`, etc. on standalone files outside the application directory structure?

**Comment by abiogenesis-now** [comment]
related: https://github.com/ksonnet/ksonnet/issues/13

**Comment by hausdorff** [comment]
I think there are valid reasons to want to do something like `ks apply default -f components/whatever.jsonnet`, especially during development. I do buy that `ks apply -f rando.jsonnet` (_i.e._, with no environment argument) does not have a compelling use case, though.

I think this is true of all our env-or-files commands. So I would like to propose we just make the environment name required on all of them.

**Comment by abiogenesis-now** [comment]
I can address the command-line docs https://github.com/ksonnet/ksonnet/pull/106/files or someone can open up a separate PR, let me know what you two prefer

**Comment by jessicayuen** [comment]
btw, thinking more on this last night --

I think it makes sense that we make the standard for apply, delete (any command that talks to a remote) `ks apply dev -c guestbook` or what not. However, for show -- I think there is still a fair use case for `ks show -f somefile.jsonnet`, since show is not dependent on any environment configurations.

Thoughts?

**Comment by abiogenesis-now** [comment]
If`somefile.jsonnet` imports parameters, would you use the values from `components/parameters.jsonnet`? That could work...

**Comment by hausdorff** [comment]
@abiogenesis-now This is in response to a conversation we had with @seh, actually. I think this is going to be the plan of record.
