### ISSUE TITLE
CLI reference needs index page

### ISSUE THREAD

**Issue by kstewart** [ksonnet/ksonnet#101]
While the `ks` commands are documented and styled nicely on their own, we should have either the README or some other index page be the "landing page" that links out to all the individual entries. Expecting people to browse the file structure on GitHub is a poor experience IMO.

**Comment by jessicayuen** [comment]
@abiogenesis-now's new README links to [this](https://github.com/ksonnet/ksonnet/tree/master/docs/cli-reference#command-line-reference) page, is it what you want?

**Comment by kstewart** [comment]
Yes. Thanks!
