### ISSUE TITLE
Rethink `ks init` parameters

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#114]
`ks init` takes an argument.  In many cases this will be the subdir of the application itself.  

Example: I have a github org and I want the ks dir to be under that. In that case, "application name" isn't quite right.  "config dir name" is probably more appropriate.  But it is more than just the dir name as this name gets put into the "name" field in app.yaml.

Specifically: if I have an app called "caribou" I'll probably call `ksonnet init` from the root of the github repo for caribou.  If I call `ks init caribou` I'll have a directory called "caribou/caribou" most probably.  That isn't great. But if I call `ks init k8s-config` then that sets the app name in app.yaml and we may key off of that for automatic labels and such at some point.

Perhaps we should have two arguments to `ks init`.  One that is the app name.  The second is the directory to create. We can pick good defaults for both. App name is the basename of the current directory.  The directory is something like ksconfig or something else sane.

**Comment by jessicayuen** [comment]
An alternative to this could be `ks init my-dir --name=caribou`

**Comment by bryanl** [comment]
I'd propose the opposite: `ks init caribou --dir=k8s-config`. This change would not require much surgery.
