### ISSUE TITLE
Improve output of `ks init`

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#115]
This is what I have now
 ```
$ ksonnet init config
INFO  Using context 'foo'
INFO  Creating environment 'default' with namespace '', pointing at server at address 'https://1.2.3.4'
INFO  Generating environment metadata at path '/Users/jbeda/tmp/ks/config/environments/default'
```

Somethings to improve this:
* Be clear about what is actually being done.  Something like "Creating a new app called "foo" in directory "bar" or some such
* Have a clear call to action.  Perhaps an example with `ks gen` and `ks apply`
* "using context" should also specify the kubeconfig file we are referencing.  "Using context xyz from config file abc".
* If people screw up here we should help them fix it.  Either by having them blow it away or giving them the commands.  Example: "To undo this simply delete directory xyz and rerun `ks init`.  Use flag --xyz to set the context or --abc to point at a different config file.  Try `ks init --help` for more options.

**Comment by jessicayuen** [comment]
Regarding the last point, I think we're going to need a more sophisticated error handling system before we can fully address the issue. Namely -- 
1. there's multiple points of failures currently (generating app.yaml, generating the default env, generating the app dir structure, generating the user dir structure etc.).
2. There's user failures (creating an app that exists) and program failures (failing to create a file) that doesn't have a clearly defined path of execution between them. 

We probably only want that message to show on program failures (point 2), without having to add a log message on each error individually (point 1).

For the time being, I'm going to add this log message but it might be redundant in a few places.

cc @hausdorff
