### ISSUE TITLE
Consider renaming `deployment-exposed-with-service`

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#118]
This prototype is super long.  Perhaps `deployed-service` or `deploy-and-service` or `simple-service`.

**Comment by abiogenesis-now** [comment]
two cents: I like `deployed-service` because it keeps the element of "Deployment" in there. can wait for consensus though

**Comment by hausdorff** [comment]
This is meant to be handled in #90.

**Comment by kstewart** [comment]
My vote is for `deployed-service`. It neatly captures intent.

**Comment by jbeda** [comment]
Not sure that this is the same as #90.  That issue is about the naming scheme (reverse DNS vs. repo/name@version).  This is about the specific name of this prototype.

Reopening.

**Comment by seh** [comment]
@jbeda, there is #154, taking care of changing the name in the _prototype/systemPrototypes.go_ file, as well as the documentation that mentions the prototype by name.

**Comment by jessicayuen** [comment]
Yes, confirming it works ...

```
➜  foo git:(init-namespace) ✗ ../ks prototype use deployed-service guestbook-ui \
--name guestbook-ui \
--image alpinejay/dns-single-redis-guestbook:1.0 \
--type LoadBalancer
INFO  Writing component at 'components/guestbook-ui'
```
