### ISSUE TITLE
version command has incomplete values

### ISSUE THREAD

**Issue by fabioy** [ksonnet/ksonnet#121]
After building "ks" as per instructions, running "ks version" gave the following output:

$  ks version
kubecfg version: dev-2017-11-20T15:01:34-0800
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$

Expect: version string outputs to have all data filled in (or strip out the field).

**Comment by jessicayuen** [comment]
Thanks for submitting! Related reasonings: https://github.com/ksonnet/kubecfg/issues/92

**Comment by hausdorff** [comment]
Yes. I think we should close the issue since the "fix" is expensive and the ROI is small. Open again @fabioy if you feel strongly that we should fix this, and we can discuss.
