### ISSUE TITLE
Can't pass in any params to namespace constructor

### ISSUE THREAD

**Issue by fabioy** [ksonnet/ksonnet#127]
Trying to create a namespace and specify a name and label, but errors out.

Code:

local namespace = k.core.v1.namespace;
local appNamespace = namespace.new("my-namespace"); 
.
<snip>
.
k.core.v1.list.new([appNamespace, appService, appDeployment])

Error:

$ ks show dev
ERROR Error reading /Users/fabio/go/src/github.com/heptio/raven/install/raven/environments/dev/dev.jsonnet: RUNTIME ERROR: Function expected 0 positional argument(s), but got 1
-------------------------------------------------

Expected: Being able to create a namespace with a name/label specified.

**Comment by jessicayuen** [comment]
cc @hausdorff  -- probably a `ksonnet-lib` issue?

**Comment by hausdorff** [comment]
@fabioy you probably checked out ksonnet/ksonnet before we made the switch to ksonnet-lib beta.3, and after the libraries were transitioned to beta.3. Can you pull HEAD, build, and then re-create the app?

**Comment by fabioy** [comment]
Cool. Re-sync'ed and recreated everything. That seems to fix it. I still can't label them, though (only a single param in constructor).

**Comment by hausdorff** [comment]
@fabioy Ok, let's close the issue and regroup about the constructor on slack.

**Comment by fabioy** [comment]
NVM, @hausdorff showed me correct way to apply labels:

local appNamespace = namespace
  .new(params.namespace)
  .withLabels(labels);
