### ISSUE TITLE
Remove docs dependency on `test-reg` branch of `ksonnet/parts`

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#142]
This was always supposed to be a dev branch so we didn't churn `master`. Now everything is merged into master and we'd like to center development on it.

(This probably involves cleaning up the ELK templates)

**Comment by jessicayuen** [comment]
This is an issue in the ksonnet/parts repo. Migrating: #50 .

Also don't think this is a blocker for release; more of a p1. We are using `master` as opposed to `test-reg` as of #151 . On a quick search of the CLI repo, I could not identify any other `test-reg` references.
