### ISSUE TITLE
A single `SpecificationSchema` should be able to have multiple "types" of template

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#16]
_From @hausdorff on September 7, 2017 23:25_

In other words, it doesn't make much sense to have multiple templates that are essentially the same, but written in Jsonnet, YAML, and JSON. A better idea is to have a single prototype be able to (possibly) take multiple forms, and maybe default to Jsonnet.

_Copied from original issue: ksonnet/kubecfg#117_

**Comment by jessicayuen** [comment]
@hausdorff -- is this ticket still relevant? Or should we rephrase it as remove showing options for "YAML" and "JSON"?

**Comment by bryanl** [comment]
Jsonnet will be the only prototype format
