### ISSUE TITLE
ks version missing/incorrect data

### ISSUE THREAD

**Issue by kstewart** [ksonnet/ksonnet#170]
```
kubecfg version: dev-2017-11-28T11:52:46-0800
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$
```

Expected:

1. Version of ksonnet tool itself (e.g. 0.7.0)
1. client-go version looks wrong

**Comment by jessicayuen** [comment]
ok, after some investigation.

1. The version of the ksonnet binary will be reflected as soon as I make a release cut documented here: https://github.com/ksonnet/ksonnet/blob/master/CONTRIBUTING.md#make-a-release. This will have to happen after the code freeze thursday.
2. See explanation in https://github.com/ksonnet/ksonnet/issues/121

I've opened a PR to change the name of `kubecfg` to `ksonnet` #171.

**Comment by bryanl** [comment]
Looks like this comes from upstream:

```go
gitCommit    string = "$Format:%H$"    // sha1 from git, output of $(git rev-parse HEAD)
```

They have a build process that preprocesses files.

**Comment by jessicayuen** [comment]
Turning this into a release checklist:
- [ ] Create `v0.6.0` tag
- [ ] Create the Github release
- [ ] Update homebrew to install `v0.6.0`
