### ISSUE TITLE
[docs] Update the summaries for ksonnet-related Github repos

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#184]
Since these are pretty much all public.
I don't have permissions to change some of these. **Open to suggestions/rewording, just want to make sure this gets done, for a polished look.**

Currently:

| Repo Title | Needs change? | Summary |
| ----- | ----- | ----- |
| ksonnet | N (?) | A CLI-supported framework that streamlines writing and deployment of multi-cluster Kubernetes configurations. |
| parts | N (?) | A collection of ksonnet registries, libraries, and prototypes that enable reuse of common Kubernetes configurations |
| ksonnet-lib | Y | ~(technical preview) Simplify working with Kubernetes~<br>Codegen for Kubernetes-API-compatible Jsonnet libraries |
| homebrew-tap | N | Homebrew tap for installing ksonnet software |

I think I need @hausdorff 's help for `ksonnet-lib` and @jbeda 's help for `homebrew-tap`. Thx! 

Screenshot so you're clear on what i'm talking about:

<img width="922" alt="screen shot 2017-11-30 at 5 58 46 pm" src="https://user-images.githubusercontent.com/25401650/33464646-2ac01890-d5f8-11e7-805b-90cbc16da524.png">

**Comment by jessicayuen** [comment]
I think `homebrew-tap` may be OK as it exists, because it'll likely be extended to install more than `ks` (i.e. if `kubecfg` ever needed a homebrew recipe, it'd probably go there)

**Comment by abiogenesis-now** [comment]
ah ok, that makes sense @jessicayuen ! We can leave that as is

**Comment by jbeda** [comment]
Yeah -- I'm thinking we'll help get kubecfg into homebrew soon-ish.  Will reach out to @anguslees to see what he thinks.

**Comment by anguslees** [comment]
Sg. There's been a homebrew recipe floating around for ages, I just don't
know what I'm supposed to do with it (not a Mac user).

**Comment by tv42** [comment]
Hi. This seemed like an appropriate issue to piggyback on. Please explain the relationship between https://github.com/ksonnet/ksonnet and https://github.com/ksonnet/kubecfg in the documentation.
