### ISSUE TITLE
[quickstart][demo] Move Guestbook container images to the 'heptio-images' registry

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#185]
A lot of our stuff is pulling an image from my personal container registry (e.g. `alpinejay/dns-single-redis-guestbook:0.4`) which might sketch people out. 

We should probably (?) move these to `gcr.io/heptio-images` to be more "official".

cc @k8k we can tag team on this tomorrow (I'll link you to my repo so you can build the images and push them, since I don't have permissions)

In short:
- [x] Push images for demo/tutorial to `heptio-images`
- [x] Update README instructions (and website)

**Comment by abiogenesis-now** [comment]
oh shoot forgot that you are out tmrw--sorry @k8k! i'll get someone else with permissions to help out

**Comment by kstewart** [comment]
@abiogenesis-now ask @chuckha to assist you.
