### ISSUE TITLE
Summarize release description

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#189]
For inspiration:

https://github.com/ksonnet/kubecfg/releases

**Comment by hausdorff** [comment]
I think we should include docker builds as part of the release instructions. @abiogenesis-now, thoughts? [Relevant doc](https://github.com/ksonnet/ksonnet/blob/master/docs/release.md)

**Comment by hausdorff** [comment]
cc @chuckha who is interested in the release process.

**Comment by hausdorff** [comment]
Oh. We don't have a standard dockerfile. Sorry, this is not trivial, then. Let's open another issue and triage it.
