### ISSUE TITLE
Issue with redis-stateless prototype

### ISSUE THREAD

**Issue by rdodev** [ksonnet/ksonnet#193]
```
bash-3.2$ ks prototype describe redis-stateless
ERROR Line in prototype heading comment is formatted incorrectly; '@shortDescription' is not
recognized as a tag. Only tags can begin lines, and text that is wrapped must
be indented. For example:
  // @description This is a long description
  //   that we are wrapping on two lines
```

```
bash-3.2$ ks version
ksonnet version: dev-2017-11-30T12:41:53-0800
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$
```

**Comment by rdodev** [comment]
Issue was resolved by updating ksonnet go repo and rebuilding binary (which was only a day old). I would think it would be a good idea to add a disclaimer to tutorial setup for users that somehow have `ks` already installed to update to latest (or a particular version) of `ks`.

**Comment by kstewart** [comment]
Actual resolution is to not push release binaries for work that is still under development. Process issue.
