### ISSUE TITLE
Package list/install is awkward

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#195]
When we do a `ks pkg list` we get this:

```
NAME      REGISTRY  INSTALLED
====      ========  =========
mysql     incubator
nginx     incubator
apache    incubator
mariadb   incubator
memcached incubator
mongodb   incubator
tomcat    incubator
efk       incubator
node      incubator
postgres  incubator
redis     incubator
```

But to install I have to type `ks pkg install incubator/redis`.  The conversion from 2 columns to `<registry>/<name>` is awkward.  I have to put a slash there and reverse the tokens.

Also, I can specify a version on install but that isn't anywhere in pkg list.  I'm guessing most users won't ever use the version?

**Comment by jessicayuen** [comment]
Approaching this with something of the form: `ks pkg install redis incubator --version=v1.2`.

Most users probably won't use the version unless they specifically need an older package. The latest version is used by default.

**Comment by jessicayuen** [comment]
After more consideration with @bryanl -- we'll actually be swapping the column placements in `ks pkg list`. Because `ks pkg install incubator/redis` is slightly more clean than `ks pkg install redis incubator`. If anyone has any disagreements, feel free to let me know here ...
