### ISSUE TITLE
Consider switching to dep from govendor

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#197]
It is the new hotness and seems to be what folks are converging on...

**Comment by kstewart** [comment]
... and also what we have internally decided to standardize on at Heptio.

**Comment by jessicayuen** [comment]
May want to hold off on this one until #215 is addressed.

**Comment by anguslees** [comment]
See also open issues like https://github.com/kubernetes/client-go/issues/318

Last time I tried (a few weeks ago), `dep` cost me a day of fiddling and then I went back to `govendor`.  I would be delighted to hear that things have improved.
