### ISSUE TITLE
Contributing fixes to tour website

### ISSUE THREAD

**Issue by lblackstone** [ksonnet/ksonnet#210]
I found a few mistakes while going through the [tour](https://ksonnet.io/tour/), but I don't see a way to report issues specific to the website, or a repo where I could submit a PR directly. You might consider making the website repo public and adding a link.

Cool demo though! 👍

**Comment by hausdorff** [comment]
@lblackstone Mmm, that's an interesting point, thanks for bringing it up. cc @abiogenesis-now, @bryanl.

In the meantime, do you mind sharing those mistakes?

**Comment by lblackstone** [comment]
Yeah certainly, wasn't sure if this was the right place for it.

1. https://ksonnet.io/tour/params - Under number 1, path should be `environments/default/params.libsonnet`
1. The list mentioned in https://ksonnet.io/tour/component-3 wasn't visible in my code window (top right), even after scrolling all the way down. I was able to see it after resizing that pane, so the scrollbar seems to be cutting off early.

Cut off
![cut off](https://user-images.githubusercontent.com/9253463/33685819-02242056-da90-11e7-9af9-7948a25f0822.png)
Resized pane
![resized](https://user-images.githubusercontent.com/9253463/33685842-197182b2-da90-11e7-9346-f66d3f289149.png)

3. https://ksonnet.io/tour/jsonnet - The instructions `At the end of the appDeployment definition, add .withReplicas(5)` are probably not explicit enough. https://ksonnet.io/tour/modify-1 mentions that the user should remove the `;` and paste the following, which is less ambiguous.
4. https://ksonnet.io/tour/modify-2 - Might want to provide a little explanation or a link to some docs for the mapContainers function. That bit of code will probably be confusing to a user that isn't familiar with functional programming.
5. https://ksonnet.io/tour/paramfiles - The quoted line 
`local params = std.extVar("__ksonnet/params").components["demo"];` 
doesn't exactly match the actual file text
`local params = std.extVar("__ksonnet/params").components.demo;`.

**Comment by abiogenesis-now** [comment]
Thank you @lblackstone for noting these issues! We'll fix them ASAP, and also discuss either open-sourcing the ksonnet site itself, or having a clearer channel for feedback.

**Comment by abiogenesis-now** [comment]
Forgot to close out this issue--these particular issues were fixed!
