### ISSUE TITLE
Consider supporting `ks param add`

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#211]
Frequently people would like to add params to a component. We should consider supporting this scenario.

**Comment by bryanl** [comment]
Can't you do a `ks param set component name value` for any item? Does this need to be more explicit or are you referring to something else?

**Comment by jessicayuen** [comment]
Yes, so `param set` currently allows adding of new params:

```
➜  foodir git:(master) ✗ ../ks param list
COMPONENT    PARAM         VALUE
=========    =====         =====
guestbook-ui containerPort 80
guestbook-ui image         "alpinejay/dns-single-redis-guestbook:0.3"
guestbook-ui name          "guestbook-ui"
guestbook-ui replicas      1
guestbook-ui servicePort   80
guestbook-ui type          "LoadBalancer"
➜  foodir git:(master) ✗ ../ks param set guestbook-ui newparam 20
INFO  Parameter 'newparam' successfully set to '20' for component 'guestbook-ui'
```

We can probably close this ticket.

**Comment by hausdorff** [comment]
It's a question of explicitness rather than functionality. The main question is: do we think it's confusing to ask people to use `param set` instead of `param add`? I think yes, but I'm maybe a 3/10 on adding the latter command rather than more docs for the first.
