### ISSUE TITLE
Discuss whether we should use Tiller's version of API object sorting

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#212]
Specifically, sorting = the order of the Kubernetes API object definitions in a given manifest, so that dependencies (e.g. namespaces) are created first

**Helm code**: https://github.com/kubernetes/helm/blob/master/pkg/tiller/kind_sorter.go
**Our code**: https://github.com/ksonnet/ksonnet/blob/2169ce8baf09ef5403f4d5e6eb0e4f1c65df88a9/utils/sort.go

The Helm/Tiller code calls out basically all the objects by name, whereas we only specify certain types and squish the rest in the middle.

**This might be a non-issue, just thought I'd flag it since someone brought it up in the #ksonnet channel on Kubernetes slack.**

**Comment by bryanl** [comment]
I like that Tiller's sorting is explicit and easy to follow. With the introduction of CRDs hopefully there won't be too many new types introduced in the foreseeable future.

**Comment by hausdorff** [comment]
CRDs should make it _harder_ to sort with an explicit ordering in general, right?

**Comment by redbaron** [comment]
@hausdorff , why? CRD definitions go first. Any unknown resource kinds (== coming from CRD) should go before any resource  type which can creates container (Deployment, Daemonset, Job,CronJob, etc...) , as it is generally running containers which act on CRDs

**Comment by bryanl** [comment]
We're moving closer to what kubectl does, so this is no longer in scope.
