### ISSUE TITLE
Move common components to `ksonnet/client`

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#215]
`ksonnet/ksonnet` and `ksonnet/kubecfg` are meant to share a number of very critical components. In November, we "temporarily" hard-forked the two projects, with the intention that after we shipped, we'd come back and "un-fork" the important parts into a common repository `ksonnet/client`.

This work is yet to remain. The critical pieces to put in the shared part are:

- [ ] Garbage Collection (mostly located in `pkg/kubecfg` specifically in `apply.go`)
- [ ] Merge logic (this needs to be solidified and written)
- [ ] API object sorting logic (mostly in `sort.go`, makes sure _e.g._ namespaces get deployed before deployments)
- [ ] Jsonnet builtins

Less critical but still important are:

- [ ] `validate` business logic and command (_e.g._, `openapi.go`).
- [ ] Object-walking logic (_i.e._, the logic we use to find all the API objects to send to the server, mostly located in `acquire.go`)
- [ ] Discovery client logic (mostly in `client.go`)
- [ ] Server interface logic (mostly in `meta.go`; might also want to write the code that retrieves and caches the schema, which we will use to generate ksonnet-lib based on what's in the server).
- [ ] Image resolver (lets us resolve a container image to a hash, _e.g._, `nginx:latest` -> `DEADBEEF`)
- [ ] Registry abstraction we use to interface with Docker registries (mostly `registry.go`)
- [ ] All the code for `version`

Not very important to the business objectives, but perhaps still worth doing:

- [ ] Various chunks of `root.go` (_e.g._, the code to create/use k8s clients, and so on)
- [ ] Logging stuff
- [ ] **[Hard and time consuming, possibly without much benefit]** Refactoring all the commands so that they only parse flags and call a common library for all app logic.

**Comment by jessicayuen** [comment]
Looks good, think adding on we can also move out other less critical stuff like
- [ ] Integration tests: common mock NS, mock Client logic (`integration_suite_test.go`)
- [ ] `examples/`, `lib/` packages entirely.

**Comment by jessicayuen** [comment]
- [ ] use `dep` instead of `govendor`?

**Comment by anguslees** [comment]
- [ ] jsonnet builtins?
