### ISSUE TITLE
Allow object literal params

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#218]
Right now, if a param is an object, it will cause the rewriter to break in some cases, since it doesn't know how to write objects back.

When go-jsonnet gets an AST writer, we should use it to rewrite the params file, which will resolve this issue "for free."

**Comment by hausdorff** [comment]
We are getting this feedback relatively frequently, _e.g._ [here](https://kubernetes.slack.com/archives/C6JLE4L9X/p1515738017000070):

> how do you deal with large number of params? e.g. if you I to set `resources` (`limit` + `requests`) that's 4 additional params. Use object? But then I cannot use that with `ks param set`, right? Cause now it seems that I'll have a deployment function with 15+ function args

**Comment by bryanl** [comment]
Ksonnet lib has an AST printer which can handle objects.
