### ISSUE TITLE
How can components inherit the namespace from the environment?

### ISSUE THREAD

**Issue by jlewi** [ksonnet/ksonnet#222]
Since namespace is a required namespace parameter, is it possible to reference that value in my components to set the namespace?

In the prototype examples it looks like namespace is hardcoded e.g. [nginx example](https://github.com/ksonnet/parts/blob/9d78d6bb445d530d5b927656d2293d4f12654608/incubator/nginx/examples/nginx.jsonnet)

**Comment by jessicayuen** [comment]
+ @bryanl Pretty important, let's put this at a p1.

**Comment by abiogenesis-now** [comment]
realized private-convo slack is not super helpful, copy-pasted the text (although it's basically just a rehash of the issue title):
> also I know prototypes can specify defaults that are constants. right now redis prototype has a mandatory `namespace` field. Is it reasonable to want `namespace` to be optional, and autopopulated by the `env`’s namespace at runtime (`ks apply`) if not specified?

**Comment by jessicayuen** [comment]
@jlewi  Using the same `nginx` context, the current way of working around this is to specify the component file as follows:

```
local params = std.extVar("__ksonnet/params").components.nginx;

k.core.v1.list.new([
  nginx.parts.deployment.simple(params.namespace, ...),
  nginx.parts.service(params.namespace, ...),
])
```

And subsequently in your environment's `environments/<name>/params.libsonnet` file, you can set the namespace value.

Ex, in your "dev" environment you might set `environments/dev/params.libsonnet`  to:
```
...
nginx +: {
  "namespace": "dev",
}
...
```
and in your "prod" environment you might set `environments/prod/params.libsonnet`  to:
```
...
nginx +: {
  "namespace": "dev",
}
...
```

I agree that it's not very polished, though. We should be able to reference the environment's namespace without explicitly setting it in the `params.libsonnet` file again.
