### ISSUE TITLE
Prototypes should specify which version of k.libsonnet they are using

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#223]
Not an urgent issue, because as far as I know, there aren't imminent plans for any version *beyond* `ksonnet.beta.3`, but we'll need to address versioning at some point.

Copied from Slack convo:

> sorry if this is already in the design doc---but what happens if one prototype is written using `ksonnet.beta.3` and another prototype is written using `ksonnet.beta.2`, given that there is (as far as I can tell) only one `k.libsonnet` inside `environments/default/.metadata`? 
>
> Should a prototype always have its own nested `k.libsonnet`, or should it specify it ksonnet version in `parts.yaml` and only pull things in if necessary?

Likely the second (the former suggestion is super inefficient), which means that a given ksonnet app might have multiple versions of `k.libsonnet` and it uses `parts.yaml` metadata to resolve to the right one.

**Comment by bryanl** [comment]
Duplicate #66
