### ISSUE TITLE
Support adding registries `ks registry add`

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#226]
Currently, users are unable to add their own registries. This limits them to a small subset of prototypes found in [ksonnet/parts](https://github.com/ksonnet/parts/tree/master/incubator).

This relates to one of the task items in #38; separating into own ticket for easier discussion.

Work remaining:

- [x] Add feature.
- [x] Add tests.

**Comment by hausdorff** [comment]
Let's keep this open until we add tests. I'll append this as a bullet to the original description.

**Comment by jessicayuen** [comment]
Tests added in #245
