### ISSUE TITLE
How to properly escape strings starting with "--"

### ISSUE THREAD

**Issue by jlewi** [ksonnet/ksonnet#235]
My component is parameterized by a string args that will be a comma separated list of strings corresponding to container args.

I can't seem to properly escape this when trying to set via the command line.

```
$ ks param set myjob8 args '--arg1=2,--arg2=3'
ERROR unknown flag: --arg1
$ ks param set myjob8 args "--arg1=2,--arg2=3"
ERROR unknown flag: --arg1
```
Am I not escaping it correctly or is this an issue with how command line arguments are processed?

**Comment by jessicayuen** [comment]
Can you try: `ks param set myjob8 args \'--arg1=2,--arg2=3\'`?

**Comment by jlewi** [comment]
That works but introduces an extra set of quotes.

```
    "myjob8": {
      args: "'--arg1=2,--arg2=3'",
    },
```

**Comment by bryanl** [comment]
You could try `ks param set myjob8 args -- --arg1=2,--arg2=3`

**Comment by jlewi** [comment]
> You could try ks param set myjob8 args -- --arg1=2,--arg2=3
That worked thank you.
