### ISSUE TITLE
ksonnet.io website is not available

### ISSUE THREAD

**Issue by redbaron** [ksonnet/ksonnet#256]
therefore all tutorials and extra documentation is not working.

There is also no link to join ksonnet.slack.com, so GH issues seem to be only way to let you know :)

**Comment by redbaron** [comment]
http://ksonnet.io shows unrelated website. https://ksonnet.io is not available

**Comment by bryanl** [comment]
It is up and running again.

**Comment by jbeda** [comment]
Also wrt ksonnet.slack.com -- we've deprecated that in favor of the #ksonnet channel on slack.k8s.io.  Where did you see the reference to ksonnet.slack.com?  We should fix that up.

**Comment by TamikoT** [comment]
@jbeda looks like it's still in the main README. Will fix now.

**Comment by lblackstone** [comment]
@TamikoT Oops, didn't notice your comment and opened a PR to fix already ^
