### ISSUE TITLE
Automatically generate the `std.extVar` and  `“__ksonnet/components”` when in ksonnet directory

### ISSUE THREAD

**Issue by bryanl** [ksonnet/ksonnet#259]
Generate the external variables so jsonnet sources using can properly resolve `std.extVar` calls for ksonnet components.

**Comment by hausdorff** [comment]
Is this an error for ksonnet/ksonnet? It seems like it shoudl be reported in the vscode repository.

**Comment by bryanl** [comment]
It was reported here so it could be added to the project.
