### ISSUE TITLE
Comparison with kapitan

### ISSUE THREAD

**Issue by mumoshu** [ksonnet/ksonnet#261]
Not only kubecfg but [kapitan](https://github.com/deepmind/kapitan) also seems like an alternative to this project to ksonnet in regard to the fact that it utilizes jsonnet for kubernetes configuration.

A simple comparison between the two (or even among other alternatives too) in the doc or readme would be helpful for newcomers to choose an appropriate tool for their job, and more importantly, emphasize the strong point(s) of ksonnet.

Probably (1) a planned helm integration and (2) the package registry support (3) an already-wider-adoption than alternatives(afaik kubeflow already adopted it) would be advantages of ksonnet?

**Comment by bryanl** [comment]
After a casual review, it looks like kapitan is similar in scope to [kubecfg](https://github.com/ksonnet/kubecfg). Have you taken a look at that? It may be helpful to add some of the other applications in our space to our documentation to better inform our developers of how we fit in the ecosystem.

**Comment by discordianfish** [comment]
Hi,

evaluating options to generate manifests and confused by kubecfg vs ksonnet too. Indeed kaptain looks similar to kubecfg and I guess can be considered a competing approach.

But what I don't really understand is kubecfg vs ksonnet. I like that kubecfg doesn't require code generation with a cli but I don't understand possible downsides of that approach. Would be super useful to have a comparision for these.

**Comment by jessehu** [comment]
One difference I found is kubecfg doesn't support parameters in CLI. e.g. ksonnet supports using '--image' and '--type' to specify the corresponding template variable in the jsonnet template file:
```
# Autogenerate a basic manifest
ks generate deployed-service guestbook-ui \
  --image gcr.io/heptio-images/ks-guestbook-demo:0.1 \
  --type ClusterIP
```
