### ISSUE TITLE
use /swagger.json from apiserver for api-spec

### ISSUE THREAD

**Issue by redbaron** [ksonnet/ksonnet#264]
`ks init` already has access to $KUBECONFIG, it can use it to download /swagger.json to generate metadata.

So it should do something along the lines:
```
kubectl get  --raw /swagger.json | jq '.info += {version: .info.version|sub("\\d+$";"0")}' > /tmp/swagger.json
ks init myapp --api-spec=file:/tmp/swagger.json
```

**Comment by bryanl** [comment]
This is an in-progress idea. We are currently reworking generating the k8s.libsonnet file and I thought this made a lot of sense.

**Comment by hausdorff** [comment]
This was enabled at one point, and then it was disabled for reasons I forget. It's pretty simple to do in itself, we already retrieve the swagger.json for `ks validate`, and the gen code should "just work".

**Comment by redbaron** [comment]
Looking at the same thing from another angle: if swagger.json is provided, no $KUBECONFIG should be needed.

**Comment by hausdorff** [comment]
@redbaron Completely agree.
