### ISSUE TITLE
ksonnet init should work without internet access

### ISSUE THREAD

**Issue by redbaron** [ksonnet/ksonnet#266]
Even if I am using swagger.json, it attempts to access internet, which makes it harder to run ks init in CI to test packages/prototypes:

```
Get https://api.github.com/repos/ksonnet/parts/commits/master: dial tcp 192.30.253.116:443: getsockopt: connection refused
```

**Comment by bryanl** [comment]
Hey, I'm going to close it as it's a dupe of #204
