### ISSUE TITLE
Building via Make

### ISSUE THREAD

**Issue by nikolay** [ksonnet/ksonnet#27]
What is the proper way to build via Make? At this point, I get an error due to `kubecfg` missing, but, then, which version of `kubecfg` should I fetch?

Everything installs properly via `go get`, but that does not allow me to install a specific version of `ksonnet`, which is my requirement.

I apologize, but I'm not experienced much with the Go toolchain.

**Comment by nikolay** [comment]
So, I figured out that I need to do `go get -d` before running `make`, but then I get this errro:

```
$ go get -d
$ make
go build -ldflags="-X main.version=dev-2017-10-23T08:04:10-0700 "  .
# _/Users/nkolev/Downloads/ksonnet-0.5.0
./main.go:36:19: cannot use logFmt (type "github.com/ksonnet/kubecfg/vendor/github.com/sirupsen/logrus".Formatter) as type "github.com/sirupsen/logrus".Formatter in argument to "github.com/sirupsen/logrus".SetFormatter:
	"github.com/ksonnet/kubecfg/vendor/github.com/sirupsen/logrus".Formatter does not implement "github.com/sirupsen/logrus".Formatter (wrong type for Format method)
		have Format(*"github.com/ksonnet/kubecfg/vendor/github.com/sirupsen/logrus".Entry) ([]byte, error)
		want Format(*"github.com/sirupsen/logrus".Entry) ([]byte, error)
./main.go:40:8: undefined: cmd.ErrDiffFound
make: *** [kubecfg] Error 2
```

Please, excuse my go ignorance, something that I'm doing incorrectly is probably beyond obvious, but I'm trying to build [asdf](https://github.com/asdf-vm/asdf) plugins for all ksonnet tools, and I'm blocked on this.

**Comment by jessicayuen** [comment]
@nikolay, apologies but the `ksonnet` tool hasn't had an official release yet. The releases you were seeing resulted from Github's "import" feature when creating the `ksonnet/ksonnet` project from `ksonnet/kubecfg` last week. We've fixed this issue now (by removing the bad releases), and will update the README shortly.

I'd advise you to use the `ksonnet/kubecfg` releases for the time being, as `ksonnet/ksonnet` is still in development phase.

**Comment by nikolay** [comment]
@jessicayuen Thank you!
