### ISSUE TITLE
Create darwin binaries and make the available via brew

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#270]
See https://twitter.com/sebgoa/status/949384204088848389.

**Comment by sebgoa** [comment]
ok so looks like you have a tap `https://github.com/ksonnet/homebrew-tap`
and the README does say `brew install ksonnet/tap/ks`

but the kubeflow readme points to https://github.com/google/kubeflow

**Comment by jbeda** [comment]
Ah -- good point.  We should let the kubeflow folks know.

Also, looks like https://goreleaser.com/ might be a good tool to use here...

**Comment by sebgoa** [comment]
I did

**Comment by jaxxstorm** [comment]
There's an example goreleaser here if you need it: https://github.com/jaxxstorm/change-aws-credentials/blob/master/.goreleaser.yml

Happy to send a PR

**Comment by caarlos0** [comment]
Creator of goreleaser here, let me know if you need any help 🍻

**Comment by jbeda** [comment]
@caarlos0 goreleaser should work pretty well.  The one rough spot is that we enforce PRs for making changes to all of our repos (along with a `signed-off-by` line) and so the "auto create commit for brew" doesn't work for us.  I instead have `goreleaser` going to a fork and then have folks edit that fork.  Would be just as easy to write out the brew file to the dist directory and leave it as an exercise to the reader to create a PR for the tap for that.

**Comment by caarlos0** [comment]
@jbeda seems pretty doable...

**Comment by caarlos0** [comment]
Maybe tomorrow I take a look on that :) (I'll be traveling for the next many hours)

**Comment by jbeda** [comment]
No hurry! What we have now is at least workable. Thanks for a great utility!

**Comment by caarlos0** [comment]
@jbeda does https://github.com/goreleaser/goreleaser/pull/503 solves the issue for you?

**Comment by jbeda** [comment]
Yes! That looks like it'll help a bunch!
