### ISSUE TITLE
ks pkg installs fails if pkg doesn't contain any subdirectories

### ISSUE THREAD

**Issue by tomwilkie** [ksonnet/ksonnet#276]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

```
$ ks registry add kausal  https://github.com/kausalco/public
$ ks pkg install kausal/klumps
ERROR open /Users/twilkie/Documents/src/github.com/kausalco/private/production/kausal/vendor/klumps/.gitignore: no such file or directory
```

From my reading of the code, if seems to rely on the pkg containing subdirectories to create the pkg root directory. If I make the directory vendor/klumps manually, it succeeds.

**What you expected to happen**:

The command to succeed without error.  

**How to reproduce it (as minimally and precisely as possible)**:

See above instructions

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
```
$ ksonnet version
kubecfg version: (dev build)
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$
```
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:08:42Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-gke.0", GitCommit:"86d3ac5eaf57223302c95e7d9fc1aeff55fb0c15", GitTreeState:"clean", BuildDate:"2017-11-08T21:42:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tomwilkie** [comment]
Have added subdir to klumps now, so repro instructions won't quite work.  But should be easy to reproduce.

**Comment by hausdorff** [comment]
@tomwilkie Interesting, thanks for the report. I wonder if rather than changing the behavior, we might just make the error message more informative. Something like:

```
ERROR: Not a valid library. Could not find a `parts.yaml` file.
```

**Comment by hausdorff** [comment]
@tomwilkie Got it. I don't know that we ever got very crisp on what constitutes a directory, so this sounds like a bug, then.

**Comment by bryanl** [comment]
ksonnet supports this in 0.11+
