### ISSUE TITLE
Omitting `pkg install` without a version can install an invalid version

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#284]
The contract of `pkg install` is that we will install a valid version of some package. For example, `ks pkg install incubator/foo@v0.0.1` works when `v0.0.1` is a valid version of the package `incubator/foo`.

The problem is: currently, if a user specifies something like `ks pkg install incubator/foo`, the version will default to `@master`, and the installation will succeed. But, `@master` is only a valid version if your registry specifically lists `master` as a valid version of that library. So there are two bugs here:

1. We do not validate the version of `pkg install` with the current registry.
1. We default to `@master`, when instead we should probably have an `@latest` construct, which applies to the most recent version specified in the registry. _This_ should be the default.

**Comment by jessicayuen** [comment]
2. is not necessarily an issue. I think it depends on the philosophy of how we want to approach `master` for the parts library.

I think equally common are projects that: 
1. Designate `master` as the production / latest release and develop in a 'develop' branch, with release tags for in-between releases. Or,
2. Develop in `master` and have release tags / `latest` for production releases.

If we go with approach 1, if will solve that problem.

**Comment by hausdorff** [comment]
That's true, but not all of our registries will be based on `git`. For example #232. I personally think that registry manager implementations should decide what `@latest` means.

**Comment by seraptoufektsi** [comment]
Ghj

**Comment by bryanl** [comment]
Package management has been overhauled. This is no longer an issue.
