### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#29]
Migrated from [here](https://github.com/ksonnet/kubecfg/issues/87)

This involves:

- [ ] Updating the ksonnet README.
- [ ] Adding `ks` to the ksonnet site (possibly move it to ksonnet.io).
- [ ] ~Adding a "case studies" section.~ Using the tutorial for this, for now.

**Comment by abiogenesis-now** [comment]
@hausdorff can you assign this to me so it's on my radar? I don't think I have permissions

**Comment by abiogenesis-now** [comment]
in my queue for today

**Comment by abiogenesis-now** [comment]
see https://github.com/ksonnet/ksonnet/pull/99, going to make an additional one for the "concepts" reference. This is for the sake of people who don't read the tutorial.
