### ISSUE TITLE
Implement standard dockerfile

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#291]
/kind feature

In the past, we've released docker images _ad hoc_. People ask us for this pretty frequently, so we should (1) implement a standard dockerfile, and (2) document it as part of the release checklist.

@chuckha has been asking for it internally also.

**Comment by chuckha** [comment]
My use case is for [sonobuoy's Makefile](https://github.com/heptio/sonobuoy/blob/master/Makefile#L59). This generates a bunch of YAML from ksonnet. This works just fine as is, but it outputs kubernetes API groups circa 1.6. We need to support the latest and these older API groups no longer work for us.

**Comment by bryanl** [comment]
I was thinking about how this would work and we'll have to solve an issue before marking this as complete. Building an image with ksonnet in it is trivial. The harder piece is ensuring you have a properly configured context as paths for certificates and keys may not be the same.
