### ISSUE TITLE
Upgrade to client-go version 6

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#297]
`ks` is running on client-go version 3. It's probably time we upgrade.

**Comment by jessicayuen** [comment]
`ks` is upgrade to client-go 5 now. 5 > 6 requires some substantial change due to the removal of `SwaggerSchema`, which we're very reliant on currently. Putting this task on hold while I work on more pressing issues.

**Comment by bryanl** [comment]
Closing in favor of #396
