### ISSUE TITLE
Generate ksonnet-lib from multiple Kubernetes versions.

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#30]
Migrated from [here](https://github.com/ksonnet/kubecfg/issues/118).

Currently, we support only generating ksonnet-lib from Kubernetes build v1.7.0. We should expand support for generating ksonnet-lib for more than one Kubernetes build.

**Comment by abiogenesis-now** [comment]
bumping to p0 because otherwise users with K8s 1.8 clusters won't be able to deploy things like Deployments without modifying core `k8s.libsonnet`
