### ISSUE TITLE
ks param set when used with boolean does not create string value

### ISSUE THREAD

**Issue by cliveseldon** [ksonnet/ksonnet#311]
/kind bug

In prototype
```
@optionalParam withRbac string false Whether to include RBAC setup
```
creates params.libsonnet with

```
withRbac: "false",
```

**What happened**:
```
ks param set seldon-core withRbac false
```
creates

```
withRbac: false,
```
which is a JSON boolean rather than a string.

**What you expected to happen**:

Consistent behaviour. Should set "false" in params file

**How to reproduce it (as minimally and precisely as possible)**:
As above with bool-like parameter

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
ksonnet version: 0.8.0
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$

- Kubernetes version (use `kubectl version`):

N/A

**Comment by bryanl** [comment]
I'm thinking about how we can tackle this issue. ksonnet-lib/jsonet are not typed, so we can't easily tell what type an item should be. The easiest solution is to introduce a flag to `ks param set` to enforce the type. Jsonnet does provide a `std.type` method so we can guess based on an existing value, but that would assume we have a good initial value to work from. 

Here is where this is happening in the code. 

https://github.com/bryanl/ksonnet/blob/use-app-targets-by-default/pkg/kubecfg/param.go#L96

**Comment by jessicayuen** [comment]
I think the problem here is mainly the inconsistencies between the `prototype create / generate` and the `ks param set` behavior. Either we decide to set booleans as strings in `ks param set` or set the proper boolean param in `generate`. I'm favoring the latter.

**Comment by cliveseldon** [comment]
This still seems to happen in:

```
ks version
ksonnet version: 0.11.0
jsonnet version: v0.10.0
client-go version: 
```
