### ISSUE TITLE
Generated YAML in random order

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/ksonnet#314]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:

`ks show` is generating the components in a random order. This makes checking in the YAML content difficult.

**What you expected to happen**:

For the generated YAML to be in non-random order.

**Environment**:
- ksonnet version (use `ks version`): 1.8.0
- Kubernetes version (use `kubectl version`): -

**Comment by harishanchu** [comment]
Is this fixed?
