### ISSUE TITLE
Authentication error against GKE

### ISSUE THREAD

**Issue by giannello** [ksonnet/ksonnet#317]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
`ks apply` fails with an authentication error when running against a GKE cluster. Works fine against a local minikube
```
$ ks apply development --dry-run
INFO  Updating services test-service (dry-run)
ERROR Error updating services test-service: services "test-service" is forbidden: User "system:anonymous" cannot get services in the namespace "development": No policy matched.
Unknown user "system:anonymous"
$ ks apply minikube --dry-run
INFO  Updating services test-service
$
```

**What you expected to happen**:
`ks apply` should configure the resources on the GKE cluster as well as the minikube instance

**How to reproduce it (as minimally and precisely as possible)**:
Initialize a new ksonnet app
Add an environment pointing at a GKE cluster
Apply some changes

**Anything else we need to know?**:
`kubectl apply` works as expected on both GKE and minikube

**Environment**:
- ksonnet version (use `ks version`):
tested with the following
```
giuseppe@rauch:~$ ks version
ksonnet version: 0.8.0
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$
```
and
```
ksonnet version: dev-2018-02-12T12:17:39+0100
jsonnet version: v0.9.5
client-go version: 1.8
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7-gke.1", GitCommit:"192ccad06d24af9828cbf42330e1d915cb586406", GitTreeState:"clean", BuildDate:"2018-01-31T21:39:04Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jlewi** [comment]
How are you authenticating to your GKE cluster? e.g. can you share your Kube config file?

I'd suggest doing the following

```
ks show ${ENV} -c ${COMPONENT} > /tmp/component
kubectl apply -f /tmp/component
```

If you get the same error then its likely not a ksonnet issue but an issue with not being properly configured to authenticat to your GKE cluster.

**Comment by giannello** [comment]
@jlewi just tested again on 0.9.2, and yes the issue is there.
I've added an environment with `ks add development --context development --namespace test`, and it shows up correctly in `ks env list`
```
NAME        KUBERNETES-VERSION NAMESPACE       SERVER
====        ================== =========       ======
development v1.7.0             test            https://[redacted]
```

however, applying fails
```
$ ks apply --dry-run development
INFO  Updating clusterrolebindings test-crb (dry-run)
ERROR Error updating clusterrolebindings test-crb: clusterrolebindings.rbac.authorization.k8s.io "test-crb" is forbidden: User "system:anonymous" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: No policy matched.
Unknown user "system:anonymous"
$
```

Manually specifying the context, however, fixes the authentication issue.
```
$ ks apply --dry-run development --context development
INFO  Updating clusterrolebindings test-crb (dry-run)
$
```

I guess the mapping between the ksonnet environment and the kube context is not handled, and has to be manually specified. Not sure if this can be considered an issue or just needs to be more explicit in the documentation.

**Comment by bryanl** [comment]
We don't store the context with the environment because context names could be different across users. I'm going to close this issue and create a documentation issue that says we must make this clearer.
