### ISSUE TITLE
tutorial document as linked from Google seems semi-broken?

### ISSUE THREAD

**Issue by stevemcghee** [ksonnet/ksonnet#322]
when searching for ksonnet from Google:
https://www.google.com/search?q=ksonnet+examples

i come across (5th link):
https://ksonnet.io/docs/tutorial.html

which shows text at the top:
{{define "content"}}

which seems.. imperfect.

its probably supposed to be:
https://ksonnet.io/docs/tutorial

maybe add a redirect?

**Comment by abiogenesis-now** [comment]
Thanks for raising this issue, we'll look into it!

**Comment by abiogenesis-now** [comment]
@stevemcghee The issue should be fixed (though you might need to clear your cache to see the update). Thanks for the heads up!
