### ISSUE TITLE
Add the ability to consume Service Accounts to ksonnet

### ISSUE THREAD

**Issue by elsonrodriguez** [ksonnet/ksonnet#332]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>
/kind feature

**What happened**:
Most kubernetes clients can connect via Kubeconfig, Serviceaccount, or default to a local unauthenticated port. Ksonnet requires a kubeconfig, which requires that one be generated within a pod prior to use, otherwise this error occurs:
```
ERROR No current context found. Make sure a kubeconfig file is present
```

**What you expected to happen**:
Ksonnet should be able to consume service account tokens.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to run ksonnet in a pod with a service account but no kubeconfig.

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
```
$ ks version
ksonnet version: v0.8.0
jsonnet version: v0.9.5
client-go version: v1.6.8-beta.0+$Format:%h$
```
- Kubernetes version (use `kubectl version`):
```
 kubectl  version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-gke.1", GitCommit:"4ce7af72d8d343ea2f7680348852db641ff573af", GitTreeState:"clean", BuildDate:"2018-01-31T22:30:55Z", GoVersion:"go1.9.2b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Quentin-M** [comment]
You can most definitely generate a kubeconfig file that uses the Service Account token though.

**Comment by elsonrodriguez** [comment]
I ended up creating a container that does just this, however it's a bit of a workaround.
