### ISSUE TITLE
Consider adding client-go flags back to `diff`

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#34]
client-go exposes a bunch of interesting and useful flags for talking to the server (_e.g._, `--insecure-skip-tls-verify`).

These were removed from `diff` because it's not clear how the flags should act when given two remote clusters.

There seem to be a couple of options for dealing with this.

1. Make `diff` more like `git diff`. `git diff` only works on local copies of a remote, so something like `git diff origin/foo..bar/baz` works on local copies. To obtain those copies, users might use something like `git fetch`. This actually fits with what we want to do for environments anyway, since we want to be able to tell users when something deleted locally is still present on the cluster.
1. Somehow add them back (this has a high potential of being confusing, I think)

**Comment by giannello** [comment]
:+1: 
when diffing the local state of an environment with the remote one, it might be required to specify a `--context` option to make sure the client picks the right configuration from the kube config file.

**Comment by anguslees** [comment]
(Just for comparison, `kubecfg diff` takes the standard client-go flags but always diffs server against local - and doesn't support other combinations)

**Comment by bryanl** [comment]
`ks diff` in master has client-go flags as of #542
