### ISSUE TITLE
ks delete default fails

### ISSUE THREAD

**Issue by testphys** [ksonnet/ksonnet#342]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
bug
>
> /kind feature

**What happened**:
ks delete default throws an error after following the kubeflow user guide with kubernetes cluster on minikube
**What you expected to happen**:
ks delete default deleting the app from the cluster
**How to reproduce it (as minimally and precisely as possible)**:
follow user guide for kubeflow

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
ksonnet version: 0.9.0
jsonnet version: v0.9.5
client-go version: 1.8
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bryanl** [comment]
Would you mind posting the error message if you can?

**Comment by testphys** [comment]
Sorry. Here it is.
Following the user guide on a minikube cluster, `ks delete default` resulted in `Error strconv.Atoi: parsing "": invalid syntax` for ksonnet v0.8.0 and in `Error Parse major version failed for` for ksonnet v0.9.0.

It's related to ksonnet/ksonnet#272 and should have been fixed for v0.9.0.

**Comment by jessicayuen** [comment]
This appears to be an issue where ksonnet is failing if the Major / Minor Server Version isn't provided. We're not currently handling parsing of the GitVersion - I'll look into getting this fixed.
