### ISSUE TITLE
Public Git Repository Setup

### ISSUE THREAD

**Issue by christopherhein** [ksonnet/ksonnet#352]
> /kind question

How would you set up a public ksonnet project's repository, whenever I `ks init app` it will automatically add my current context to the `environments/default` directory. Is there a best practice for sharing these configurations so that I don't commit my apiserver's host name to the world?

My current implementation is to `.gitignore` the `environments/*` and have the user use `ks env add default` when they start using the project, is that right?

Thanks!

**Comment by bryanl** [comment]
Currently, there isn't a great way. The plan is to introduce another file that can be maintained locally that can override app.yaml environment settings. The current timeline for this is by the end of next month.

**Comment by christopherhein** [comment]
Fantastic, thank you!
