### ISSUE TITLE
Intergrate with or borrow from kubecrt

### ISSUE THREAD

**Issue by nikolay** [ksonnet/ksonnet#36]
There's a significant ongoing effort to develop robust Helm Charts for composable infrastructure. It would be nice to be able to integrate with Helm Charts in a way [kubecrt](https://github.com/blendle/kubecrt) already does it - by transpiling a charts config into a manifest, which then can be used in ksonnet.

Right now, I'm doing this via a build process, but maybe in addition to supporting YAML, JSON, and Jsonnet, a [kubecrt](https://github.com/blendle/kubecrt) charts' config would be a worthy add-on.

**Comment by bryanl** [comment]
We are currently researching helm chart components in #522. Closing this issue as the work will be tracked there.
