### ISSUE TITLE
Implement package management

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet#38]
Roughly, this involves:

- [x] Implement the `app.yaml` schema, where we store registry and dependency information for an app
- Implement `ks registry`
  - [x] Implement `registry.yaml` schema for general registries to expose what libraries they keep track of
  - [x] Implement the registry protocol for github.
  - [x] Implement `ks registry describe`
  - [ ] Implement `ks registry add`
  - [ ] Implement `ks registry remove` **[won't ship for feature complete]**
  - [x] Implement `ks registry list`
- Implement `ks pkg`
  - [x] Implement the `parts.yaml` schema, where we store registry and dependency information for a library
  - [x] Implement dependency cache disk data structure
  - [x] Implement `ks pkg describe`
  - [ ] Implement `ks pkg search`
  - [x] Implement `ks pkg install`
  - [x] Implement `ks pkg list`
  - [ ] Implement `ks pkg refresh`

**Comment by hausdorff** [comment]
I said _PARTIAL_ fix, GitHub!

**Comment by hausdorff** [comment]
Downgrading to `p1`, since the rest of the commands are not critical to ship right now.

**Comment by jlewi** [comment]
Doesn't seem like `ks registry add` is implemented yet.

**Comment by jessicayuen** [comment]
Thanks for noting - The task box appears to be incorrectly checked. I've corrected the state.

**Comment by jessicayuen** [comment]
@bryanl @hausdorff Going to work on adding `ks registry add`.

**Comment by bryanl** [comment]
The newer package work supersedes this work
