### ISSUE TITLE
ks pkg install does not install the correct branch set in the registry

### ISSUE THREAD

**Issue by ankushagarwal** [ksonnet/ksonnet#398]
/kind bug

**What happened**:
```
ks init myapp
cd myapp
VERSION=v0.1.0-rc.0
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/${VERSION}/kubeflow --version=${VERSION}
ks pkg install kubeflow/core
```

`kubeflow/core` pkg is installed from the branch `master` of github.com/kubeflow/kubeflow/

**What you expected to happen**:
`kubeflow/core` pkg to be installed from the branch `${VERSION}` of github.com/kubeflow/kubeflow/

**Environment**:
- ksonnet version (use `ks version`):
```
% ks version
ksonnet version: 0.9.2
jsonnet version: v0.9.5
client-go version: 1.8
```

cc @jlewi

**Comment by jlewi** [comment]
I think this might have been user error on my part. I think you need to specify the reftag on the ks install step

```
ks pkg install kubeflow/tf-job@${VERSION}
```

**Comment by veliborfrobas** [comment]
Which one do you exactly mean: "tf-job@${VERSION}"
ks version
ksonnet version: dev-2018-07-13T11:42:24+0200
jsonnet version: v0.9.5
client-go version: 1.8

**Comment by GuessWhoSamFoo** [comment]
@veliborfrobas Version refers to the kubeflow releases https://github.com/kubeflow/kubeflow/releases
