### ISSUE TITLE
[Feature Request] Can we have Ksonnet command to Output to a file ?

### ISSUE THREAD

**Issue by charlesa101** [ksonnet/ksonnet#400]
/kind feature

Will be cool to have `ksonnet` command to output to file
`ks output -f filename.yml`

**Comment by redbaron** [comment]
does `ks show $env >filename.yml`  work for you?

**Comment by charlesa101** [comment]
yes! it does that's what i am using for now! :-)

**Comment by bryanl** [comment]
Instead of adding code for this, we're encouraging people to use pipes to handle this functionality. `ks show` outputs to stdout.
