### ISSUE TITLE
[polish] Make sure CLI commands have the right verbs

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#41]
There are some potential CLI changes we need to make, based on the demo. Feel free to contest any one of these:

- [x] Rename (or at least alias) `ks prototype use` to `ks generate` 
- [ ] Figure out how we want to deal with the other `ks prototype *` commands. Do we keep `prototype` in the command, and if so, is that inconsistent with `ks generate`?

There might be more questions as we finish up ksonnet params and environments, but want to make sure this is on our radar for the demo next week.

**Comment by abiogenesis-now** [comment]
cc @jessicayuen @hausdorff

**Comment by jessicayuen** [comment]
Good points, we should also review the output of the logging messages of each command to make sure they're not too verbose (or lacking).

**Comment by abiogenesis-now** [comment]
Is there a demo and/or kubecon milestone we can use to organize these issues?

If you'd like, I can handle this---I'd just need admin permissions for this repo ;P

**Comment by jessicayuen** [comment]
@abiogenesis-now  We have a feature complete milestone `0.7.0 - Feature Complete`. Gave you permission!
