### ISSUE TITLE
Question: import not available kubeflow/core/all.libsonnet and other problems with master

### ISSUE THREAD

**Issue by jlewi** [ksonnet/ksonnet#420]
@bryanl Are there any known issues with the code @ [e0e68f8f1542b4775933cf0e2ddcec28b96bb409](https://github.com/ksonnet/ksonnet/commit/e0e68f8f1542b4775933cf0e2ddcec28b96bb409)

I'm encountering a problem when running `ks show`. Here's the full [stack trace](https://gist.github.com/jlewi/6a20d724aa35e5909692cc0b3600854b)

Looks like a problem with the vendor directory not being picked up.

These are the [steps](https://github.com/kubeflow/kubeflow#steps) I followed.

Also is there a bug [here](https://github.com/ksonnet/ksonnet/blob/master/pkg/env/data.go#L27); should there be a ";" at the end of the line

```
local k = import "k.libsonnet"
```

**Comment by pdmack** [comment]
Same, https://github.com/kubeflow/kubeflow/issues/566#issuecomment-378470994
