### ISSUE TITLE
ksonnet's kubernetes version resolver needs to be expanded to work with multiple distributions of Kubernetes

### ISSUE THREAD

**Issue by fxue** [ksonnet/ksonnet#427]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
>
> /kind feature

**What happened**:
Found this while resolving Kubeflow [issue](https://github.com/kubeflow/kubeflow/issues/521).
copying it here.

**What you expected to happen**:
correct k8s picked up

**How to reproduce it (as minimally and precisely as possible)**:

```
➜  ks version
ksonnet version: 0.9.2
jsonnet version: v0.9.5
client-go version: 1.8
```
getting a different 404 error now. 
```
➜  ks show ${KF_ENV} -c kubeflow-core
ERROR Recieved status code '404' when trying to retrieve OpenAPI schema for cluster version 'v3.9.14' from URL 'https://raw.githubusercontent.com/kubernetes/kubernetes/v3.9.14/api/openapi-spec/swagger.json'

```
seems like the problem is with using the openshift version instead of k8s version
```
➜ oc version
oc v3.9.7
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://api.starter-us-west-1.openshift.com:443
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657
```

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):0.9.2
- Kubernetes version (use `kubectl version`):v1.9.1

**Comment by pdmack** [comment]
This is due to the fact that the ks client retrieves the version from the Kubernetes master swagger.json endpoint. However, for OpenShift this value is its own (e.g., v3.9.14). Once the version is parsed it's assumed to be registered here:
```
metadata/lib/clusterspec.go:    k8sVersionURLTemplate = "https://raw.githubusercontent.com/kubernetes/kubernetes/%s/api/openapi-sp
metadata/lib/clusterspec.go:    versionURL := fmt.Sprintf(k8sVersionURLTemplate, cs.k8sVersion)
``` 
which wouldn't apply for OpenShift.

**Comment by bryanl** [comment]
In ksonnet 0.10, the logic for finding the schema has changed. If ksonnet can read swagger.json, it'll use that file. There is a possibility that will backported to 0.9, but that won't happen until after 0.10 is released.

**Comment by mattf** [comment]
fyi, this is still broken in 0.10.0-alpha2. a workaround is:
```
ks init ${APP_NAME} --api-spec=version:$(oc version | grep ^kubernetes | head -n1 | sed 's/kubernetes \(.*\)+.*/\1/')
```

**Comment by bryanl** [comment]
I've updated the title of this issue to capture the larger case.
