### ISSUE TITLE
Regression from 0.9.1: Getting "ERROR Unauthorized" when using --token parameter in 0.9.2

### ISSUE THREAD

**Issue by alaqelsplk** [ksonnet/ksonnet#430]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**What happened**:

We use the service account token parameter to deploy to Kubernetes within our CI/CD process. This works in 0.9.1 but regressed in 0.9.2.

**What you expected to happen**:
We expected that the token worked and authorized the CI/CD container to deploy the service.

**How to reproduce it (as minimally and precisely as possible)**:
ks apply $env --token=<token>

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
ksonnet version: 0.9.2
jsonnet version: v0.9.5
client-go version: 1.8
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T20:49:12Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.10", GitCommit:"044cd262c40234014f01b40ed7b9d09adbafe9b1", GitTreeState:"clean", BuildDate:"2018-03-19T17:44:09Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bryanl** [comment]
This whole section was re-worked in 0.10. I've added integration tests to catch this issue so it hopefully doesn't creep in again.
