### ISSUE TITLE
In-cluster API access

### ISSUE THREAD

**Issue by inc0** [ksonnet/ksonnet#431]
Question/Freature request.

With kubectl or certain clients k8s allows to access to cluster from within pod. Is it possible to use ksonnet from within cluster to create resources?

https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

**Comment by inc0** [comment]
Alternative would be to write k8s manifests to file (or stdout) and kubectl create -f them.

**Comment by inc0** [comment]
Figured it out:)

` ks env add default --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) --server=https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}`
`ks apply default --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)`

**Comment by IronPan** [comment]
Thanks inc0 for figuring this out. It's really helpful as I am facing the same need. 

Does it make sense for ks CLI to automatically choose between kubeconfig and env variable, so that users don't need to pass in them manually? I would imaging using ks in a pod could be common.
