### ISSUE TITLE
Links to cli-reference are broken on core-concepts page (website)

### ISSUE THREAD

**Issue by Maerville** [ksonnet/ksonnet#440]
Hi all

Seems like links pointing to commands like **ks generate**, **ks apply**, **ks param** etc. are broken on this page https://ksonnet.io/docs/concepts

links are pointing to https://docs/cli-reference#ks-prototype
instead of https://ksonnet.io/docs/cli-reference#ks-prototype

Also link to Manifest anchor is broken
In Application paragraph it points to https://ksonnet.io/#manifests , while it should point to https://ksonnet.io/docs/concepts#manifest

**Comment by bryanl** [comment]
We are reviewing / fixing issues with the site links. An update will be issued soon.

**Comment by GuessWhoSamFoo** [comment]
Fixes are committed; pending deploy of new site.
