### ISSUE TITLE
ksonnet 1.10 no longer uses environments/env/main.jsonnet

### ISSUE THREAD

**Issue by jessesuen** [ksonnet/ksonnet#446]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**:

There appears to be a change in behavior in ksonnet 0.9 vs. 0.10 (from tip of master)… 0.9 seems to rely the presence of main.jsonnet as the entrypoint for emitting the objects, where as 0.10 ignores the file completely.

I'm not sure if this is expected. If so, 0.10 should stop auto-generating main.jsonnet and base.libsonnet.

In the absence of main.jsonnet, is there a equivalent behavior for the having some sort of jsonnet entrypoint of an environment?

**Comment by redbaron** [comment]
if it is true, what is the file now  which emits objects?

**Comment by jessesuen** [comment]
From slack:

bryanl [1:32 PM]
@jessesuen yes. the main.jsonnet/base.jsonnet was a regression. When I get back from vacation tomorrow, I’ll push a fix.

main.jsonnet/base.jsonnet is in a weird space, but it should not be hard to fix.
