### ISSUE TITLE
ks param list command shows error if components/params.libsonnet has null or array.

### ISSUE THREAD

**Issue by jsakai** [ksonnet/ksonnet#447]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
ks param list command shows error if components/params.libsonnet has null or array.
```
vim components/params.libsonnet
{
  global: {
  },
  components: {
    ‘test-v1': {
      envs: null,
      },
  },
}

$ ks param list
ERROR get all component params for : Found an unsupported param AST node type: *ast.LiteralNull
```
```
vim components/params.libsonnet
{
  global: {
  },
  components: {
    ‘test-v1': {
      envs: [],
      },
  },
}

$ ks param list
ERROR get all component params for : Found an unsupported param AST node type: *ast.Array
```

**Environment**:
- ksonnet version (use `ks version`):
$ ks version
ksonnet version: 0.9.2
jsonnet version: v0.9.5

**Comment by jessesuen** [comment]
I think this may be resolved in 0.10, since I am using array params in 0.10, but get the "Found an unsupported param AST node type: *ast.Array" error with ks 0.9.

**Comment by jessesuen** [comment]
To be clear, 0.10 built from tip, not alpha.1 which has a bunch of other param related bugs.

**Comment by bryanl** [comment]
Arrays should work as of right now. I'm created a fix for nulls. (thanks for the use case)
