### ISSUE TITLE
param::import is broken in alpha version

### ISSUE THREAD

**Issue by Maerville** [ksonnet/ksonnet#475]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
ks show default -c ${JOB_NAME} is throwing error

ERROR find objects: find objects for test-job in /: RUNTIME ERROR: couldn't open import "param://name": no match locally or in the Jsonnet library paths

**What you expected to happen**:
Expected to see YAML manifest instead

**How to reproduce it (as minimally and precisely as possible)**:
```
ks generate deployed-service guestbook-ui   --image gcr.io/heptio-images/ks-guestbook-demo:0.1   --type ClusterIP
vim components/guestbook-ui.jsonnet
```
change lines 9-11 to the following
```
local name = import "param://name";
local targetPort = params.containerPort;
local labels = {app: name};

```
and execute
`ks show default -c guestbook-ui
`

**Anything else we need to know?**:
Bug doesn't appear on 0.9.2 version

**Environment**:
- ksonnet version (use `ks version`):0.10.0-alpha.1
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bryanl** [comment]
The import `import "param://name"` nomenclature should only be used in prototypes. It will be replaced when the component is generated with the options you passed in as arguments.

**Comment by Maerville** [comment]
Okay, here I was trying to make a minimal example :)

Here is initial example (having kubeflow installed)

```
JOB_NAME=dist-mnist
ks generate tf-job ${JOB_NAME} --name=${JOB_NAME}
ks show default -c ${JOB_NAME}
```

(following https://ai.intel.com/lets-flow-within-kubeflow/ tutorial)

**Comment by bryanl** [comment]
I have a fix for this issue. This code path isn't as robust as it should be.
