### ISSUE TITLE
Unrecognized template type 'yml'; must be one of: [yaml, json, jsonnet]

### ISSUE THREAD

**Issue by eyalzek** [ksonnet/ksonnet#476]
```
$ ks import -f foo.yml
ERROR parse template type: Unrecognized template type 'yml'; must be one of: [yaml, json, jsonnet]
```

`.yml` is a fairly common extension for YAML files and should probably be added to that list. Alternatively, a mimetype check/linter can be run on the file to properly detect if it's supported, instead of assuming it by the extension.

**Comment by bryanl** [comment]
Currently, it uses HTTP Content-Disposition when it can, but that wouldn't have found `.yml`. I'm fixing the obvious case and will leave this open to add real mime type detection in a future revision.
