### ISSUE TITLE
ks disk-based registry can't generate prototype

### ISSUE THREAD

**Issue by inc0** [ksonnet/ksonnet#480]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I've tried to use disk-based registry

result:
`ERROR no prototype names matched 'kubeflow-core'`

**What you expected to happen**:

Not an error

**How to reproduce it (as minimally and precisely as possible)**:
```
git clone https://github.com/kubeflow/kubeflow.git /opt/kubeflow
ks init kfl
cd kfl
ks registry add kubeflow /opt/kubeflow/kubeflow
ks pkg install kubeflow/core
ks generate kubeflow-core kubeflow-core
```

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
jsonnet version: v0.10.0
client-go version: 1.8
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bryanl** [comment]
ksonnet 0.10.0 does not have this regression.

![2018-04-26_08-14-19](https://user-images.githubusercontent.com/240/39305109-ed4d12e2-4929-11e8-8ede-7988b326f6bf.png)
