### ISSUE TITLE
Detect if param is sent from cmd (import "param://xxx")

### ISSUE THREAD

**Issue by lqj679ssn** [ksonnet/ksonnet#489]
Hi, I'm dealing with [kubeflow issue](https://github.com/kubeflow/kubeflow/pull/688).
Now I want to send a param `modelStorageType` through cmd. But this param has a default value. So I can also choose to not send this param through cmd (and get the default value `cloud`).

The code to deal with the param is 
`local modelStorageType = import "param://model_storage_type"`.

Anyone can tell me how to detect if `model_storage_type` is sent from cmd?

**Comment by bryanl** [comment]
Hello, 

We're currently working through the 0.10 release, so this won't be looked at until later today or Monday.

**Comment by bryanl** [comment]
Use @param instead of @optionalParam when you want required parameters.
