### ISSUE TITLE
ks param set converts values consisting of string of digits to numerics

### ISSUE THREAD

**Issue by arsenvlad** [ksonnet/ksonnet#492]
/kind bug

**What happened**:
Trying to create parameter with a string of digits (e.g. "0", "00", "1", "2"), but ksonnet removes all double and single quotes from the all digit strings in the param file.

**What you expected to happen**:
It should be possible to create parameter with values like "0", "00" and have them stay as literal strings instead of being converted into numerics.

**How to reproduce it (as minimally and precisely as possible)**:

`ks param set component_name x "0"`

view the params file and see the double quotes removed:
    x: 0,

Using the same approach it is possible to completely break "ks param list" like this:

`ks param set component_name x "00"`

Try to list params

`ks param list component_name`

Get error: ERROR get all component params for : 20:11-12 Expected a comma before next field.

Manually remove the x: 00 value from params.libsonnet file to restore "ks param" functionality.

**Anything else we need to know?**:

It does not seem possible to use ", \", ', \', "", '', etc. to force ks param set to keep the quotes. 

For example, using 

`ks param set component_name x \'0\'
`
The value added to the params file contains multiple quotes:

x: "'0'",

**Environment**:
- ksonnet version (use `ks version`):

ksonnet version: 0.9.2
jsonnet version: v0.9.5
client-go version: 1.8

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bryanl** [comment]
I created a patch that will handle cases like `00`. As for single digits or numbers that look like floats, there currently isn't a way to provide a type hint. The values are taken from the command line as a string and then are matched with regular expressions to determine what the type is. To set `1` as a string, there would need to be a new option. I'll create a new issue for that.
