### ISSUE TITLE
ERROR No ksonnet application found on freshly cloned repos

### ISSUE THREAD

**Issue by jessesuen** [ksonnet/ksonnet#500]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**:

The pkg/metadata::Find() function attempts to locate a ksonnet app by recursively looking for the presence of a .ksonnet directory. The problem is that `.ksonnet/registries` is by default added to the `.gitignore`, which means the `.ksonnet` dir will not be checked into git. So when freshly cloning a git repo containing a ksonnet app, some ksonnet commands will fail with `ERROR No ksonnet application found`

This affects some (but not all) `ks` commands like `ks diff` which still rely on this discovery mechanism. Others like `ks env list` and `ks show <env>` are not affected. 

**What you expected to happen**:

`ks diff` should work without the presence of .ksonnet dir

**How to reproduce it (as minimally and precisely as possible)**:

```
cd someapp
rm -rf .ksonnet
ks diff default
```

**Environment**:
- ksonnet version (use `ks version`): v0.10.1

**Comment by bryanl** [comment]
Were there any commands other than diff that failed?

**Comment by abh** [comment]
"ks prototype" commands also seems to fail

```
$ ks prototype search deploy
Usage:
  ks prototype search <name-substring> [flags]

Examples:

# Search for prototypes with names that contain the string 'service'.
ks prototype search service

Flags:
  -h, --help   help for search

Global Flags:
  -v, --verbose count[=-1]   Increase verbosity. May be given multiple times.

ERROR could not find ksonnet app
```

**Comment by bryanl** [comment]
Closing due to age.
