### ISSUE TITLE
ks param set incorrectly matches float (even with --as-string)

### ISSUE THREAD

**Issue by e-zhang** [ksonnet/ksonnet#509]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When trying to set a param for a semver version, `ks param set` returns an error for strconv.ParseFloat invalid float. Looks like the regex pattern for float matches repeated periods (`(\.[0-9]+)*`).
When trying with the `--as-string` flag, same error is thrown. It looks like the asString flag is not preserved in the EnvParamSet. 

`ERROR set params: strconv.ParseFloat: parsing "0.0.1": invalid syntax`

**What you expected to happen**:
Set param correctly as string

**How to reproduce it (as minimally and precisely as possible)**:
`ks param set <component> <param> 0.0.1`
`ks param set <component> <param> 0.0.1 --as-string`

**Anything else we need to know?**:
Regression in 0.10.1, works in 0.10.0.

**Environment**:
- ksonnet version (use `ks version`): 0.10.1
- Kubernetes version (use `kubectl version`): 1.9.4

**Comment by stjohnjohnson** [comment]
I believe this only happens with semver versions that start with 0
