### ISSUE TITLE
Is there a guide to setup ksonnet registry service locally?

### ISSUE THREAD

**Issue by cheyang** [ksonnet/ksonnet#510]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>
> /kind feature

/kind question

**What happened**:

I'm trying to use ksonnet registry service without internet connection. I'm wondering how to work it out. Thanks.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
- Kubernetes version (use `kubectl version`):

**Comment by GuessWhoSamFoo** [comment]
@cheyang It is possible to do this based on inspection of the source: https://github.com/ksonnet/ksonnet/blob/master/pkg/actions/registry_add.go#L108

To add a registry from file system, add to the path containing `registry.yaml`.
e.g. `ks registry add <registry name> /path/to/registry`

This will be documented in the near future.

**Comment by cheyang** [comment]
Thank you.

**Comment by bryanl** [comment]
Work has been committed to the site
