### ISSUE TITLE
Introduce helm component

### ISSUE THREAD

**Issue by bryanl** [ksonnet/ksonnet#522]
ksonnet should be able to consume helm charts as a component type.

## [Helm Registry](https://docs.google.com/document/d/1FcK8pDqj_9EFjNVr9e_t9WemouQpS9ix-r0AxNDB_nM/edit?usp=sharing)

- [x] ksonnet will expose Helm repositories as registries
- [x] Helm based registries can expose their contents as prototypes #664
- [x] Helm registries can manage multiple Chart releases simultaneously. #672
- [x] Helm registry should attempt to cache entries

### Helm upgrade

A ksonnet user should be able to upgrade a chart to the specific version or the latest release.

**Comment by burdiyan** [comment]
One thing to take into account that is specific to Helm is hooks: https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md

I think that replicating this functionality should not be a goal, so maybe Ksonnet should interact with Tiller to install Helm charts, instead of rendering them locally.

**Comment by bryanl** [comment]
I'm actually leaning towards making helm charts registries and using the helm rendering engine to generate something ksonnet can understand. The goal for this is not to replicate all of helm inside of ksonnet, but to instead make charts (and their dependencies) available to ksonnet.

**Comment by burdiyan** [comment]
Some of Charts inside stable Helm repository are using hooks as a crucial part of the chart. For example `mongodb-replicaset` chart is using post-install hook to form the actual ReplicaSet after all nodes are up.

**Comment by bryanl** [comment]
@burdiyan after reviewing the hooks, the first version of this feature will not include support for hooks. ksonnet's operating model is declarative and hooks are imperative, so this fit is not obvious.

**Comment by burdiyan** [comment]
@bryanl Make sense for the initial implementation. Although would be great if ksonnet fail when trying to import a chart with hooks. Or at least a warning.

**Comment by bryanl** [comment]
@burdiyan that is the plan. Working out when  and where to fail right now.
