### ISSUE TITLE
Passing a list of arrays to k.core.v1.list.new() doesn't work

### ISSUE THREAD

**Issue by giannello** [ksonnet/ksonnet#536]
/kind bug

**What happened**:
Returning `k.core.v1.list.new([array1, array2])` from a component fails with
```
ERROR find objects: decode unstructured: json: cannot unmarshal array into Go value of type map[string]interface {}
```
Using `k.core.v1.list.new(array1 + array2)` works as expected

**What you expected to happen**:
Ksonnet should return a list containing all the objects in `array1` and `array2`

**Environment**:
- ksonnet version (use `ks version`):
```
ksonnet version: 0.10.2
jsonnet version: v0.10.0
client-go version: 1.8
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.0", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-04-19T17:08:34Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bryanl** [comment]
In PR #547, ksonnet will now handle arrays returned by components by wrapping them in a Kubernetes list.

**Comment by redbaron** [comment]
This issue is different from what #547 is doing. Here `k.core.v1.list.new([array1, array2])` is called,  so no naked list is returned from component. Problem here is `k.core.v1.list()` expects flat list, but @giannello calls it with nested arrays

**Comment by bryanl** [comment]
The issue is that you should be doing `array1 + array2`. Supporting nested arrays is complexity I'd like to avoid. We'll support the simple case, and rely on the developer to make their code fit the simple case.

**Comment by giannello** [comment]
Makes totally sense, thanks.
