### ISSUE TITLE
Autogenerate .gitignore file (e.g. for libs or hidden files)

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#55]
Upon `ks init`.

**Comment by jessicayuen** [comment]
Offline discussion with @hausdorff:

This is less straightforward than we initially scoped and will need some design decisions. For example, if we ignore `vendor/` and `.metadata/` directories ... how will a new user that's checking out the project pull in these dependencies?

Obviously, we can just not have `.gitignore` and check in everything but we will be checking in `1.7mb` files and this is not optimal either.

**Comment by abiogenesis-now** [comment]
yeah luckily there's `app.yaml` which means there will still be some way of pulling in `vendor/` after the fact (e.g. via `ks dep restore` or some other new CLI command)

but agreed that that is another possibly complicated thing to implement

**Comment by jessicayuen** [comment]
related: #217
