### ISSUE TITLE
Pretty print output of `ks dep list`

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#56]
I know Alex has a plan for this, just don't want it to slip through.

It should:
* indicate which libraries have been downloaded to local
* have something that can be easily copy/pasted into `ks dep get`

e.g. something along the lines of:
```
Registry      library@latest release 
---------- -----------------------
*incubator     redis@0.3.0     
incubator   elasticsearch@0.1.1    
incubator     prometheus@0.5.2     
*incubator     mysql@0.3.0 
```

**Comment by jessicayuen** [comment]
Going to close this ticket since @hausdorff opened a related "super" ticket: #67
