### ISSUE TITLE
Parsing error when using computed fields

### ISSUE THREAD

**Issue by giannello** [ksonnet/ksonnet#571]
/kind bug

**What happened**:
When generating an array of elements using list comprehension, computed fields trigger a parsing error
```
$ ks show default
ERROR find objects: <extvar:__ksonnet/components>:10:8-9 Unexpected: ("{", "{") while parsing field definition

      {{
$
```

**What you expected to happen**:
A list of objects with computed keys should be generated.

**How to reproduce it (as minimally and precisely as possible)**:
```
local k = import "k.libsonnet";

local domain = '.example.org';
local services = ["one", "two"];

local computedServices = [
  local serviceName = service;
  local serviceUrl = service + domain;
  {[serviceName]: serviceUrl}
  for service in services
];

std.prune(k.core.v1.list.new(computedServices))
```

**Anything else we need to know?**:
Using `{serviceName:` instead of `{[serviceName]:` doesn't trigger the parsing error, but generated keys are not computed.

**Environment**:
```
ksonnet version: 0.10.2
jsonnet version: v0.10.0
client-go version: 1.8
```

**Comment by bryanl** [comment]
This is a parsing issue in the ksonnet jsonnet printer. The issue is tracked in https://github.com/ksonnet/ksonnet-lib/issues/143
