### ISSUE TITLE
--help flag gets dropped in nested commands (ks prototype preview)

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#59]
Tried to run
```
ks prototype preview --help
```
But got
```
ERROR No prototype names matched '--help'
```

Not super urgent but needs to be fixed.

**Comment by jessicayuen** [comment]
related: #21

**Comment by abiogenesis-now** [comment]
Ah sorry, didn't realize this was a dup---I'm going to close this and we can use the one you linked as the main tracking issue
