### ISSUE TITLE
Is there a ksonnet api?

### ISSUE THREAD

**Issue by q2w** [ksonnet/ksonnet#613]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>
> kind feature

**What happened**:
I want to generate components on a kubernetes cluster from process running inside a container.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
feature
**Environment**:
- ksonnet version (use `ks version`):
- Kubernetes version (use `kubectl version`):

**Comment by bryanl** [comment]
Hello, there is isn't currently a ksonnet API. I'm trying to understand what you are trying to do. You want to run ksonnet functionality without exec'ing the ksonnet binary?

**Comment by q2w** [comment]
i wanted to create kubernetes resources from a service using ksonnet. I counldn't find a way to do so. I changed my design and did using kubenetes java-client.
