### ISSUE TITLE
Retry apply if cluster return OptimisticLockErrorMsg error

### ISSUE THREAD

**Issue by bryanl** [ksonnet/ksonnet#619]
/kind bug

In some cases, it is possible that the cluster will return an out of date object to be updated. To compensate for the `kubectl` tries to apply 5 times before giving up. ksonnet should as well.

https://github.com/kubeflow/kubeflow/issues/980

**Comment by burdiyan** [comment]
We have the same issue in our CI with ksonnet that breaks our build from time to time.
