### ISSUE TITLE
New bug on 0.11.0: panic: unknown Expr1 type *ast.Conditional

### ISSUE THREAD

**Issue by kunmingg** [ksonnet/ksonnet#637]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
ks show ... throws unknown type error.

**What you expected to happen**:
show the yaml spec or output what's wrong with the component

**How to reproduce it (as minimally and precisely as possible)**:

```
export VERSION=mpi-operator
ks init testmpi
cd testmpi 
ks registry add kubeflow github.com/rongou/kubeflow/tree/${VERSION}/kubeflow
ks pkg install kubeflow/mpi-job@${VERSION}
ks generate mpi-job-simple mpi-job-simple
ks show default
```

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
0.11.0
- Kubernetes version (use `kubectl version`):

**Comment by bryanl** [comment]
Underlying issue is a conditional in an object field.

**Comment by bryanl** [comment]
Tracking upstream: https://github.com/ksonnet/ksonnet-lib/issues/146

**Comment by bryanl** [comment]
There is a PR for this: https://github.com/ksonnet/ksonnet-lib/pull/147
