### ISSUE TITLE
`ks prototype preview` doesn't seem to work for JSON and YAML

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#64]
(I'm wondering if this is because of the `extVar`?)

`ks prototype preview` works fine when the `type` is specified as `jsonnet`. However, it will error out if either `json` or `yaml` is used.

e.g. for the following command (YAML)
```
$ ks prototype preview deployment-exposed-with-service yaml \
> --name guestbookui \
> --image alpinejay/dns-single-redis-guestbook:1.1 \
> --type LoadBalancer
```
the output is:
```
ERROR preview:1:11-12 Did not expect: ":"
```

For JSON, the output is:
```
ERROR preview:8:23-24 Expected token OPERATOR but got ("}", "}")
```

**Comment by abiogenesis-now** [comment]
However, I can confirm that `ks show default` works once the component is generated.

**Comment by jessicayuen** [comment]
Going to close this. I believe @hausdorff removed the types for YAML and JSON. I did test against master, but please re-open if it's not the case!

**Comment by abiogenesis-now** [comment]
So to clarify, `prototype preview` supports jsonnet "type" only?

I just ran again and had the same error. I double checked that I rebuilt the ksonnet binary; let me know if you need help to repo
