### ISSUE TITLE
Persistent deployment update failures with "there is a meaningful conflict"

### ISSUE THREAD

**Issue by cboggs** [ksonnet/ksonnet#650]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`ks apply` fails (and never succeeds without intervention once it happens) with:
```
ERROR handle object: can't update deployments nginx: Operation cannot be fulfilled on deployments.apps "nginx": there is a meaningful conflict (firstResourceVersion: "26191208", currentResourceVersion: "26191211"):
 diff1={"metadata":{"resourceVersion":"26191211"},"status":{"$setElementOrder/conditions":[{"type":"Available"},{"type":"Progressing"}],"conditions":[{"message":"ReplicaSet \"nginx-5d97bcd8db\" is progressing.","reason":"ReplicaSetUpdated","type":"Progressing"}],"replicas":3,"unavailableReplicas":4}}
, diff2={"metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"resourceVersion":"26191195","selfLink":"/apis/apps/v1beta1/namespaces/default/deployments/nginx"},"spec":{"template":{"metadata":{"creationTimestamp":null}}},"status":{"$setElementOrder/conditions":[{"type":"Available"},{"type":"Progressing"}],"conditions":[{"lastUpdateTime":"2018-06-19T21:29:36Z","message":"ReplicaSet \"nginx-5f8bbdbf84\" is progressing.","reason":"ReplicaSetUpdated","type":"Progressing"}],"observedGeneration":1,"replicas":3,"updatedReplicas":3}}
```

**What you expected to happen**:
Successful `ks apply` with:
```
INFO Updating deployments nginx
```

**How to reproduce it (as minimally and precisely as possible)**:
This is unfortunately fuzzy, as it seems to crop up at fairly random times. I've seen it happen after:
* Modifying deployment and/or pod template labels (not entirely unexpected, this is a breaking action in some cases)
* Trying to apply a deployment that has multiple old replicaSets seems to trigger it, but only sometimes. According to the diff above, one is in a "Progressing" state, while the other is... also "Progressing"? I'm unclear on what the conflict is in this case.

**Anything else we need to know?**:
As mentioned above there are instance where even after putting `ks apply` in a loop for 30 iterations, the issue doesn't go away, which seems to indicate that mimicking the `kubectl` behavior of "retry when there's a merge issue" (#619). Then again, it seems to be a different failure mode, so that might be expected.

**Environment**:
- ksonnet version (use `ks version`):
```
ksonnet version: 0.11.0
jsonnet version: v0.10.0
client-go version:
```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-26T16:14:03Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.1", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-05-11T17:16:56Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bryanl** [comment]
We may have a fix for this in the works. I believe #619 describes the same issue.

**Comment by cboggs** [comment]
Interesting. I haven't seen a retry ever fix this particular one, as it seems to be a different failure, but I'll be pretty thrilled if the fix for #619 does take care of it. :-)

**Comment by bryanl** [comment]
I've identified a new failure type and created a PR for in #727. ksonnet wasn't doing merges properly because it wasn't comparing the proper modified document.

**Comment by cboggs** [comment]
Cool, thanks for digging in and fixing! Will gladly test an appropriate build when it's merged and follow up here.

**Comment by bryanl** [comment]
The commit is in master. Please let me know!

**Comment by csmarchbanks** [comment]
I am still seeing this issue, or something very similar using:
```
ksonnet version: 0.12.0-rc1
jsonnet version: v0.10.0
client-go version:
```

I get the error:
```
$ ks apply <env> -c <component-name>
INFO Applying services default.<component-name>
INFO Applying deployments default.<component-name>
INFO Applying deployments default.<component-name>
INFO Applying deployments default.<component-name>
INFO Applying deployments default.<component-name>
INFO Applying deployments default.<component-name>
ERROR handle object: apply conflict detected; retried 5 times
```

The change is applied to the cluster properly, but the ksonnet tool fails which makes deploying multiple components at the same time impossible.

**Comment by cboggs** [comment]
Thinking on this a bit more (BTW, @csmarchbanks and I work together, hence us flipping back and forth on this issue :-) ), I think this particular error is more likely a reemergence of #619, just with a nicer error message. 

In working on another project that needed to do lots of updates to K8s resources, I came across the "object has been modified" 419 (as referenced in the 619 issue) a _lot_. Ended up finding [this comment](https://github.com/kubernetes/kubernetes/issues/28149#issuecomment-229469157) that asserts this error is benign and can be safely ignored.

I wound up ignoring that particular error message in my other project, and I've yet to see it fail to make an expected update - though, to be fair, it's a pet project so far, so it's not exactly well-exercised.

@bryanl, what are you thoughts on ignoring that particular 419 error entirely? I know it's separate from the original error reported in this particular issue, but thought I'd ask in an open one. :-)

**Comment by bryanl** [comment]
We're going to resolve this before releasing 0.12

**Comment by csmarchbanks** [comment]
@bryanl I have a fix for this locally. Will be opening a PR in the next few days

**Comment by bryanl** [comment]
@csmarchbanks awesome. I'm curious what you found. Please open a PR.

**Comment by csmarchbanks** [comment]
@bryanl See https://github.com/ksonnet/ksonnet/pull/787 for a fix that worked for me
