### ISSUE TITLE
Support for k8s version with extra suffix 

### ISSUE THREAD

**Issue by winnietsang** [ksonnet/ksonnet#666]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug report

**What happened**:
When I run "ks apply" on IBM Cloud Private-CE, I got the following error message: 
ERROR find objects: Received status code '404' when trying to retrieve OpenAPI schema for cluster version 'v1.10.0+icp' from URL 'https://raw.githubusercontent.com/kubernetes/kubernetes/v1.10.0+icp/api/openapi-spec/swagger.json'

The error is cause by the extra suffix in the k8s version
Is it possible to add some code like these in file pkg/lib/clusterspec.go(line 30) func OpenAPI
pattern := regexp.MustCompile("v[0-9]+.[0-9]+.[0-9]+(-rc.[0-9]+)*")
version := pattern.FindString(cs.k8sVersion)
versionURL := fmt.Sprintf(k8sVersionURLTemplate, version)

**Environment**:
- ksonnet version (use `ks version`): v0.11.0
- Kubernetes version (use `kubectl version`): v1.10.0+icp

**Comment by bryanl** [comment]
We are currently revising the process for determining how to retrieve the correct version of the kubernetes schema. Closing this in favor of #427
