### ISSUE TITLE
Add dependencies to -J path

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/ksonnet#68]
@hausdorff @jessicayuen 

- **Vendor path**
  `ks apply` and `ks default` don't work for components generated from the `incubator` prototypes--*this is because `vendor/` is not included in the default jsonnet lib paths.* I'm not sure if `root.go` needs to be modified to include it or somewhere else; either way, I don't think it'll be a difficult fix.
  - [x] Adding `vendor/` to the `-J` paths in ksonnet/ksonnet.
  - [ ] Flatten out the `vendor/` directory.
  - [ ] Changing all prototypes in ksonnet/parts from `import "incubator/whatever/whatever.libsonnet"` to use `import "whatever/whatever.libsonnet"` instead.

**Comment by hausdorff** [comment]
@jessicayuen @abiogenesis-now I'd like to move this to two different issues. Since you're in an urgent meeting I hope you don't mind if I just do it.

**Comment by abiogenesis-now** [comment]
yah that's fine, feel free to close this or modify however you please

**Comment by hausdorff** [comment]
Alright, @jessicayuen @abiogenesis-now let's add `vendor/` to the ksonnet path. This will involve two steps:

1. Adding `vendor/` to the `-J` paths in ksonnet/ksonnet
1. Changing all prototypes to `import "incubator/whatever/whatever.libsonnet"` to use `import "whatever/whatever.libsonnet"` instead.

I'll update the issue. If something sounds wrong we can re-work the issue again.

**Comment by abiogenesis-now** [comment]
@hausdorff wait I think it works fine if prototypes use `import "incubator/whatever/whatever.libsonnet"` in their definitions? e.g. because of the directory structure they need that registry prefix

**Comment by hausdorff** [comment]
One more thing. Right now `vendor/` has the registry name baked into the file structure. So imports are of the form `vendor/incubator/nginx`. This is a mistake. It complicates everything (_e.g._, renaming registries) and is not materially useful for the dependencies themselves.

So, we need to flatten it out, THEN we can do the second step.

I'll update the issue.

**Comment by hausdorff** [comment]
Bumping down to p1. Flattening the `vendor/` directory is not our highest priority right now.

**Comment by hausdorff** [comment]
Bumping to P1, since #262 is P1, and that's a duplicate of this one.

**Comment by bryanl** [comment]
ksonnet adds vendor to the jsonnet path.
