### ISSUE TITLE
Allow installing package when same version is installed in another scope

### ISSUE THREAD

**Issue by shomron** [ksonnet/ksonnet#728]
It should be possible to install a package into a scope, regardless of whether that version is also installed in another scope.

Currently this is a rejected with an error along the lines of:

```
ERROR package 'incubator/nginx@40285d8a14f1ac5787e405e1023cf0c07f6aa28c' already exists.
```

**Comment by shomron** [comment]
@bryanl would you say this is closed via #744 ?

**Comment by shomron** [comment]
Actually I think there's a subtle difference between the two. We can discuss.

**Comment by shomron** [comment]
@bryanl circling back to this issue I believe the distinction is as follows:

* `ks pkg install` should allow referencing a package/version that was previously installed in another scope without any special flags
* `ks pkg install --force` would behave the same as above with one important difference: it would invalidate the cache and force re-downloading the specified package/version

Any objections?

**Comment by bryanl** [comment]
@shomron SGTM
