### ISSUE TITLE
ks import -f directory reference should ignore invalid files

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [ksonnet/ksonnet#774]
/kind feature

**What happened**:
If a directory in `components/` contains something other than a yaml, jsonnet, or json file, attempting to import the directory reference will error.

e.g.
```
ks import -f <lots_of_yaml> --module /
ERROR parse template type: Unrecognized template type 'md'; must be one of: [yaml, json, jsonnet]
```

**What you expected to happen**:
Ignore unrecognized files such as README.md or offer an option to ignore

**Comment by bryanl** [comment]
We shouldn't deal with this. You should run `ks import` on a directory that only has YAML in it.
