### ISSUE TITLE
`ks diff` should skip resource types and continue when permission is denied

### ISSUE THREAD

**Issue by HT154** [ksonnet/ksonnet#802]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I use a very locked-down k8s cluster. I have limited permissions in a single namespace. I don't have any permissions (not even list) over DaemonSet objects. `ks diff <env>` immediately errors with `ERROR daemonsets.apps is forbidden: User "<user>" cannot list daemonsets.apps in the namespace "<namespace>"`

**What you expected to happen**:
I expect `ks` to print a warning that DaemonSet objects will not be diff'd (citing the error) and continue attempting to diff all other resource types.

**How to reproduce it (as minimally and precisely as possible)**:
Create a serviceaccount in your cluster. Use a RoleBinding to assign a Role with no permissions to list/get/etc. DaemonSets. Set up your kubeconfig to use this service account. Attempt to run `ks diff <env>` on any ksonnet app (doesn't need to contain a DaemonSet).

**Environment**:
- ksonnet version (use `ks version`):
```
ksonnet version: 0.12.0-rc1
jsonnet version: v0.10.0
client-go version:
```

client-go version is blank

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by shomron** [comment]
@HT154 this issue is resolved in 0.12.0 - as well as other diff improvements. You will still see warnings when your permissions are insufficient, but the diff will go through. Upgrade and give it try!
