### ISSUE TITLE
Update `$GUESTBOOK_URL` in the Tutorial

### ISSUE THREAD

**Issue by idealhack** [ksonnet/ksonnet#806]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`$GUESTBOOK_URL` produced `http://localhost:8001/api/v1/proxy/namespaces/ks-dev/services/guestbook-ui` which is 404

**What you expected to happen**:

the correct URL should be `http://localhost:8001/api/v1/namespaces/ks-dev/services/guestbook-ui/proxy/` according to https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-services-running-on-the-cluster

**Environment**:
- ksonnet version (use `ks version`): `0.12.0-rc1`

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by GuessWhoSamFoo** [comment]
@idealhack Thanks for the report. Fix is pushed and pending merge on the website repo

**Comment by idealhack** [comment]
@GuessWhoSamFoo I forgot to mention `$PROD_GUESTBOOK_URL`, does the patch fix that already?
