### ISSUE TITLE
Ingress services in ksonnet

### ISSUE THREAD

**Issue by TheJaySmith** [ksonnet/ksonnet#825]
Howdy, 

So I am working on building a ksonnet package and when I go into the "kubectl apply" function, I get this

REROR handle object: can't update ingresses ing: Ingress in version "v1beta1" cannot be handled as a Ingress: v1beta1.Ingress: Spec: v1beta1.IngressSpec: Rules: []v1beta1.IngressRule: v1beta1.IngressRule

I have the apiService as  extensions/v1beta1 . I changed it to just "v1" with no luck. Thoughts?

**Comment by bryanl** [comment]
Would it be possible for you to share how you are defining the ingress?

**Comment by TheJaySmith** [comment]
Sure

`
ing:: {
    apiVersion: "extensions/v1beta1",
    kind: "Ingress",
    metadata: {
      name: "ing",
    },
    spec: {
     rules: [{
        host: params.url,
        http: [{
          paths: {
            backend: [
             {
              serviceName: "super",
              servicePort: 4040,
              },
            ],
          },
        }],
      }],
     },
    },

`

**Comment by bryanl** [comment]
`backend` isn't an array of objects, it's an object itself.

```json
  {
    apiVersion: 'extensions/v1beta1',
    kind: 'Ingress',
    metadata: {
      name: 'ing',
    },
    spec: {
      rules: [{
        host: params.url,
        http: {
          paths: [{
            backend: {
              serviceName: 'super',
              servicePort: 4040,
            },
          }],
        },
      }],
    },
  },
```

**Comment by bryanl** [comment]
@TheJaySmith I hope this was helpful. I'm going to close this issue now. If you have any questions, please feel free to re-open it.

**Comment by TheJaySmith** [comment]
Yep. Sorry for not responding soon. All is well. Thank you @bryanl  !!!
