### ISSUE TITLE
Ksonnet 1.0 plan/road map?

### ISSUE THREAD

**Issue by richardsliu** [ksonnet/ksonnet#862]
Hi,

What is the plan for releasing Ksonnet 1.0? When can we expect the CLI to be fully stabilized?

Thanks,
Richard

**Comment by underrun** [comment]
the roadmap is in the repo:

https://github.com/ksonnet/ksonnet/blob/master/design/roadmap.md

beyond what is in that document we don't expect significant changes to the CLI, but that being said we also don't have a current timeline to 1.0 - PRs are very welcome though :-)
