### ISSUE TITLE
ks generate creates jsonnet file with 3 spaces indents

### ISSUE THREAD

**Issue by devlounge** [ksonnet/ksonnet#866]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**What happened**:
ks generate creates jsonnet file with 3 spaces indents instead of 2 like every other files generated by ksonnet

**What you expected to happen**:
I would like a consistent whitespacing, ideally matching the standards

**How to reproduce it (as minimally and precisely as possible)**:
using ks generate

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`): v0.11.2
- Kubernetes version (use `kubectl version`): 1.10.2

**Comment by aknuds1** [comment]
Pretty sure I experienced the same.

**Comment by aknuds1** [comment]
I'm trying to solve this, but haven't got my head around the test suite yet.

**Comment by aknuds1** [comment]
I've solved the issue in PR #877 :)
