### ISSUE TITLE
Different behavior of ks tool in tour vs in cli version

### ISSUE THREAD

**Issue by jwerak** [ksonnet/ksonnet#871]
/kind bug

**What happened**:
I ran ksonnet online tour and locally via `ks` tool and it resulted in different jsonnet outputs.

Tour version:
```jsonnet
local params = std.extVar("__ksonnet/params").components.demo;
local k = import "k.libsonnet";
local deployment = k.apps.v1beta1.deployment;
local container = k.apps.v1beta1.deployment.mixin.spec.template.spec.containersType;
local containerPort = container.portsType;
local service = k.core.v1.service;
local servicePort = k.core.v1.service.mixin.spec.portsType;

local targetPort = params.containerPort;
local labels = {app: params.name};

local appService = service
  .new(
    params.name,
    labels,
    servicePort.new(params.servicePort, targetPort))
  .withType(params.type);

local appDeployment = deployment
  .new(
    params.name,
    params.replicas,
    container
      .new(params.name, params.image)
      .withPorts(containerPort.new(targetPort)),
    labels);

k.core.v1.list.new([appService, appDeployment])
```

cli (0.13.0) version:
```jsonnet
local env = std.extVar("__ksonnet/environments");
local params = std.extVar("__ksonnet/params").components["guestbook-ui"];
[
   {
      "apiVersion": "v1",
      "kind": "Service",
      "metadata": {
         "name": params.name
      },
      "spec": {
         "ports": [
            {
               "port": params.servicePort,
               "targetPort": params.containerPort
            }
         ],
         "selector": {
            "app": params.name
         },
         "type": params.type
      }
   },
   {
      "apiVersion": "apps/v1beta2",
      "kind": "Deployment",
      "metadata": {
         "name": params.name
      },
      "spec": {
         "replicas": params.replicas,
         "selector": {
            "matchLabels": {
               "app": params.name
            },
         },
         "template": {
            "metadata": {
               "labels": {
                  "app": params.name
               }
            },
            "spec": {
               "containers": [
                  {
                     "image": params.image,
                     "name": params.name,
                     "ports": [
                     {
                        "containerPort": params.containerPort
                     }
                     ]
                  }
               ]
            }
         }
      }
   }
]
```

**What you expected to happen**:
Consistent behavior 

**How to reproduce it (as minimally and precisely as possible)**:
Tour version:

Follow [online tour](https://ksonnet.io/tour/) till `generate/run` and check file `components/demo.jsonnet`

CLI version:

```bash
ks init my-app
cd my-app 
ks generate deployed-service demo \
  --image=gcr.io/kuar-demo/kuard-amd64:1 \
  --replicas=2 \
  --type=ClusterIP
cat components/demo.jsonnet
``` 

**Anything else we need to know?**:
I am wondering from where the system prototypes are comming from. I can see system prototypes in ksonnet: https://github.com/ksonnet/ksonnet/tree/master/pkg/prototype/system but the prototypes from tour seems much more interesting.

**Environment**:
- ksonnet version (use `ks version`): 
    ksonnet version: 0.13.0
    jsonnet version: v0.11.2
    client-go version: kubernetes-1.10.4
- Kubernetes version (use `kubectl version`):
    Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by aknuds1** [comment]
I noticed the same just now, it's confusing.

``` ks version
ksonnet version: 0.13.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4```

**Comment by hyww** [comment]
According to [release notes of v0.11.0](https://github.com/ksonnet/ksonnet/releases/tag/v0.11.0)
> ksonnet built-in prototypes have been reworked to not use ksonnet-lib

Pull request:
https://github.com/ksonnet/ksonnet/pull/551

Related issues:
https://github.com/ksonnet/ksonnet/issues/548
https://github.com/ksonnet/ksonnet/issues/209
