### ISSUE TITLE
Kubeflow getting panic: runtime error: invalid memory address or nil pointer dereference when kfctl.sh generate k8s

### ISSUE THREAD

**Issue by cbbba18** [ksonnet/ksonnet#883]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>
> /kind feature

**What happened**:

Running kubeflow kftctl.sh generate k8s crashes ksonnet with panic: runtime error: invalid memory address or nil pointer dereference.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1057c42]

goroutine 1 [running]:
github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.parsePaths(0xc4204cc400, 0x6, 0x1, 0xc)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/paths.go:33 +0x1f1
github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.NewCatalog(0xc4204cc400, 0xc420a56c30, 0x1, 0x1, 0x40, 0x0, 0x0)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/catalog.go:76 +0x1de
github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.GenerateLib(0xc420042180, 0x3a, 0x0, 0x0, 0x0)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/ksonnet.go:25 +0xce
github.com/ksonnet/ksonnet/pkg/util/kslib.astBuilder(0xc420042180, 0x3a, 0xc42299c000, 0x3f0dc0, 0x3ffe00, 0x0, 0x0, 0x0)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/util/kslib/ksonnet.go:87 +0x40
github.com/ksonnet/ksonnet/pkg/util/kslib.Ksonnet(0xc42299c000, 0x3f0dc0, 0x3ffe00, 0x0, 0x0, 0x0)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/util/kslib/ksonnet.go:83 +0x3fd
github.com/ksonnet/ksonnet/pkg/lib.(*defaultKsLibGenerator).Generate(0xc42218d9e0, 0xc421d99c80, 0xf, 0xc42221593a)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/lib/lib.go:62 +0x8e
github.com/ksonnet/ksonnet/pkg/lib.(*Manager).GenerateLibData(0xc422180500, 0xf, 0x2b1e380)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/lib/lib.go:106 +0x4c
github.com/ksonnet/ksonnet/pkg/app.ksLibUpdater.UpdateKSLib(0x2b1e380, 0x3942898, 0xc421d9f530, 0xc421d99c80, 0xf, 0xc421d8ae40, 0x2b, 0xc42153b0b0, 0x27, 0x25a9da5, ...)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/app/lib_updater.go:44 +0x99
github.com/ksonnet/ksonnet/pkg/app.(*baseApp).AddEnvironment(0xc421da4ee0, 0xc4222245a0, 0xc421d99c80, 0xf, 0x3620200, 0x3, 0x3)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/app/base_app.go:532 +0x4be
github.com/ksonnet/ksonnet/pkg/env.(*creator).Create(0xc42222a000, 0xc42222a000, 0xc421da4ee0)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/env/create.go:117 +0x9c3
github.com/ksonnet/ksonnet/pkg/env.Create(0x2b26400, 0xc421da4ee0, 0xc421d7c6e0, 0x16, 0x25ae36e, 0x7, 0x25ae36e, 0x7, 0xc421d99c80, 0xf, ...)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/env/create.go:42 +0x157
github.com/ksonnet/ksonnet/pkg/appinit.(*initApp).Run(0xc420a578d8, 0x35, 0x47028b0)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/appinit/init.go:91 +0x459
github.com/ksonnet/ksonnet/pkg/appinit.Init(0x2b1e380, 0x3942898, 0xc421d9f530, 0x7ffeefbffae0, 0x6, 0xc42153b0b0, 0x27, 0x0, 0x0, 0xc421d99c80, ...)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/appinit/init.go:34 +0x155
github.com/ksonnet/ksonnet/pkg/actions.(*Init).Run(0xc421d32140, 0xc421d32140, 0x0)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/actions/init.go:113 +0x140
github.com/ksonnet/ksonnet/pkg/actions.RunInit(0xc421d9f500, 0xc421c2e240, 0xe)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/actions/init.go:40 +0x5c
github.com/ksonnet/ksonnet/pkg/clicmd.runAction(0xe, 0xc421d9f500, 0x25c00fa, 0x12)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/clicmd/actions.go:118 +0x66
github.com/ksonnet/ksonnet/pkg/clicmd.newInitCmd.func1(0xc421ce0280, 0xc421cb8740, 0x1, 0x1, 0x0, 0x0)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/pkg/clicmd/init.go:156 +0x7fa
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).execute(0xc421ce0280, 0xc421cb8700, 0x1, 0x1, 0xc421ce0280, 0xc421cb8700)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc421bf3180, 0xc421c7e000, 0xc421bf3680, 0xc421bf3400)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).Execute(0xc421bf3180, 0x3942898, 0xc420046064)
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/oren.shomron/go/src/github.com/ksonnet/ksonnet/cmd/ks/main.go:48 +0x148

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
ksonnet version: 0.13.0
jsonnet version: v0.11.
- Kubernetes version (use `kubectl version`):

**Comment by mjm** [comment]
I'm seeing the same here when I just run `ks init foo-bar`

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
$ ks version
ksonnet version: 0.13.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

**Comment by mjm** [comment]
Also happens with a build of `ks` from `master`.

**Comment by AndriiNeverov** [comment]
github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/paths.go:33

ref := extractRef(*body.Schema)

seems like in some cases Schema field is not there, but SimpleSchema is. I think this is a piece of the v1.12.2 Swagger spec which is responsible for this (e.g. "dryRun" is not present in v1.9.6):

"post": {
     "description": "create a Namespace",
     "consumes": [
      "*/*"
     ],
     "produces": [
      "application/json",
      "application/yaml",
      "application/vnd.kubernetes.protobuf"
     ],
     "schemes": [
      "https"
     ],
     "tags": [
      "core_v1"
     ],
     "operationId": "createCoreV1Namespace",
     "parameters": [
      {
       "name": "body",
       "in": "body",
       "required": true,
       "schema": {
        "$ref": "#/definitions/io.k8s.api.core.v1.Namespace"
       }
      },
      {
       "uniqueItems": true,
       "type": "string",
       "description": "When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed",
       "name": "dryRun",
       "in": "query"
      }
     ],

**Comment by WenshanL** [comment]
Also seeing same problem here with k8s server version v1.12.2. 
Reverting to v1.11.4 got rid of the error.

**Comment by mro-aaskandani** [comment]
still getting panic error while trying to use the latest release(0.13.0)!

**Comment by shomron** [comment]
@mro-aaskandani the fix is not part of an official release yet - you have to compile from master to use it at this time.
