### ISSUE TITLE
Installing helm chart from custom Helm repository retrieves 0 files

### ISSUE THREAD

**Issue by jpgneves** [ksonnet/ksonnet#889]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

With a custom Helm chart repository `myrepo` containing a chart `foo`, `ks pkg install myrepo/foo` retrieves 0 files. This breaks my application as the app.yaml file is modified to include the installed chart as a library, but nothing has been downloaded.

**What you expected to happen**:

My custom chart gets properly installed in my ksonnet application.

**How to reproduce it (as minimally and precisely as possible)**:

1) Custom Helm Chart repository setup in S3 and reachable from the machine.
2) `ks repository add myrepo <repo URL>`
3) `ks pkg install myrepo/foo`

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
```
ksonnet version: dev-
jsonnet version: v0.11.2
client-go version:
```
(built from source from the v0.13.1 branch)
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"", BuildDate:"2018-10-29T07:50:18Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"freebsd/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by acesyde** [comment]
Same problem on private or public repository.

`DEBUG setting log verbosity                         verbosity-level=1
DEBUG loading application configuration from /c/Users/pfcp8316/Documents/Projects/kubernetes/package-city-ks
DEBUG loading schema version 0.3.0
DEBUG loading overrides from /c/Users/pfcp8316/Documents/Projects/kubernetes/package-city-ks
DEBUG loading overrides from /c/Users/pfcp8316/Documents/Projects/kubernetes/package-city-ks
DEBUG caching dependency                            action=registry.CacheDependency custom-name=smtp-server part=smtp-server registry=myplace version=20180830.1
INFO Retrieved 0 files
DEBUG loading application configuration from /c/Users/pfcp8316/Documents/Projects/kubernetes/package-city-ks
DEBUG loading schema version 0.3.0
DEBUG loading overrides from /c/Users/pfcp8316/Documents/Projects/kubernetes/package-city-ks
DEBUG saving app version 0.3.0                      action=baseApp.save
DEBUG writing /c/Users/pfcp8316/Documents/Projects/kubernetes/package-city-ks/app.yaml`

**Comment by waisbrot** [comment]
Also trying to use the public chart repo.

Reproduction steps based on https://ksonnet.io/docs/examples/helm/:
1. `ks init helm-test`
2. `cd helm-test`
3. `ks registry add helm-stable https://kubernetes-charts.storage.googleapis.com`
4. `ks pkg install helm-stable/wordpress`  (shows "0 files" message)
5. `ks pkg install helm-stable/wordpress`  (shows error message)

```
ksonnet version: 0.13.1
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-eks", GitCommit:"58c199a59046dbf0a13a387d3491a39213be53df", GitTreeState:"clean", BuildDate:"2018-09-21T21:00:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sh0rez** [comment]
Yes, but this happens only on Linux. Doesn't matter if precompiled or built from source. Works on osx when installing using brew. Didn't try compiling on osx.

**Comment by acesyde** [comment]
@sh0rez on linux and windows with released package

**Comment by sh0rez** [comment]
@acesyde 

> With ksonnet 0.13.0 it works
Cannot reproduce. I did the following for master, v0.12.0, v0.13.0:

```bash
# create repo, $TAG the according one of master, v0.12.0, v0.13.0
$ ks init helm-test-$TAG

# Add registry
$ ks registry add helm-stable https://kubernetes-charts.storage.googleapis.com -v

# retrieve files
$ ks pkg install helm-stable/wordpress -v
```

Every single version did the same: Retrieve no files:

<details><summary><b>master</b></summary>
<p>

```
DEBUG setting log verbosity                         verbosity-level=1
DEBUG loading application configuration from /home/shorez/work/kshelm/helm-test
DEBUG loading schema version 0.3.0
DEBUG loading overrides from /home/shorez/work/kshelm/helm-test
DEBUG loading overrides from /home/shorez/work/kshelm/helm-test
DEBUG caching dependency                            action=registry.CacheDependency custom-name=wordpress part=wordpress registry=helm-stable version=""
INFO Retrieved 0 files
DEBUG loading application configuration from /home/shorez/work/kshelm/helm-test
DEBUG loading schema version 0.3.0
DEBUG loading overrides from /home/shorez/work/kshelm/helm-test
DEBUG saving app version 0.3.0                      action=baseApp.save
DEBUG writing /home/shorez/work/kshelm/helm-test/app.yaml
```

</p>
</details>

<details><summary><b>v0.13.0</b></summary>
<p>

```
DEBUG setting log verbosity                         verbosity-level=1
DEBUG loading application configuration from /home/tbraack/work/kshelm/helm-test-13.0
DEBUG loading schema version 0.3.0
DEBUG loading overrides from /home/tbraack/work/kshelm/helm-test-13.0
DEBUG loading overrides from /home/tbraack/work/kshelm/helm-test-13.0
DEBUG caching dependency                            action=registry.CacheDependency custom-name=wordpress part=wordpress registry=helm-stable version=""
INFO Retrieved 0 files
DEBUG loading application configuration from /home/tbraack/work/kshelm/helm-test-13.0
DEBUG loading schema version 0.3.0
DEBUG loading overrides from /home/tbraack/work/kshelm/helm-test-13.0
DEBUG saving app version 0.3.0                      action=baseApp.save
DEBUG writing /home/tbraack/work/kshelm/helm-test-13.0/app.yaml
```

</p>
</details>

<details><summary><b>v0.12.0</b></summary>
<p>

```
DEBUG setting log verbosity                         verbosity-level=1
DEBUG caching dependency                            action=registry.CacheDependency custom-name=wordpress part=wordpress registry=helm-stable version=""
INFO Retrieved 0 files
DEBUG saving app version 0.2.0                      action=baseApp.save
```

**Comment by sh0rez** [comment]
Ok, I was able to fix (?) the problem. On my machine, a test called `Test_UnTgz` from package `archive` failed. It should extract a `tar.gz`, but actually did nothing.

So I started debugging and figured out that the handler function did not get called (https://github.com/ksonnet/ksonnet/blob/f6da2d5/pkg/util/archive/tgz.go#L62), because the condition of the `switch` did not evaluate to `true`. I'm not sure why, but the field `header.Typeflag` was always `48`. So I **removed the `switch`**, calling the header unconditionally. The problem went away and according to the tests there are no side-effects. 

It's weird that `48` is not listed as a possible value of `header.Typeflag` in the docs: (https://golang.org/pkg/archive/tar/#Header).

Any thoughts on this?

<details><summary><b>System info</b></summary>
<p>

```bash
# uname -a
$ Linux sh0rez 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# go version
$ go version go1.11 linux/amd64

# git rev-parse HEAD
$ 7c76c9a36caccb5261c05c5152919b6ae1badcc0
```

</p>
</details>

**Comment by waisbrot** [comment]
> It's weird that 48 is not listed as a possible value of header.Typeflag in the docs: (https://golang.org/pkg/archive/tar/#Header).

I wonder...  https://www.gnu.org/software/tar/manual/html_node/Standard.html

The `typeflag` field holds the type. It is one of the _characters_ `0..7`; not a binary representation of that number. So `'0'` ("regular file") is the decimal value 48 and `'5'` ("directory") is the decimal value 53.

**Comment by jaxxstorm** [comment]
Will there be a new release that addresses this soon? Having to build from source to get this fixed

**Comment by anselms** [comment]
I still get this error, even using the ksonnet version build from master today - does anyone know a workaround?

```
ksonnet version: dev-2019-02-02T00:03:55+0100
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```

**Comment by GuessWhoSamFoo** [comment]
@anselms What version of go are you building from?

**Comment by anselms** [comment]
That would be
```
go version go1.10.4 linux/amd64

```
