### ISSUE TITLE
Make component name an implicit argument

### ISSUE THREAD

**Issue by jbeda** [ksonnet/ksonnet#89]
Almost every prototype has a `name` param. The component also has a name. Most of the time these are the same thing and users have to repeat the name on the command line.

If instead we made the name of the component an implicit parameter into the component (and make it overridable?) then we'd reduce typing and eliminate a param per prototype.

**Comment by jessicayuen** [comment]
cc @bryanl 

For a little more context on this ticket:

There is a current command `ks generate <prototype-name> <component-name> [type] [parameter-flags] [flags]`, that  takes a `component-name` as an argument.

However, in practicality, most prototypes have a `name` parameter, as seen in the `name` flag below:
```
../ks prototype use deployed-service guestbook-ui \
--name guestbook-ui \    
--image alpinejay/dns-single-redis-guestbook:1.0 \
--type LoadBalancer
```

Note that we are passing `guestbook-ui` twice.  Joe is suggesting that the two be consolidated.

**Comment by bryanl** [comment]
@jessicayuen, the `--name` parameter could be made optional and the default can be ascertained from the prototype. This is path I'm going to explore.
