### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by daixiang0** [ksonnet/ksonnet#897]
/kind bug

**What happened**:
```
$ GOPATH=/pkgs/go make install
go build -o /pkgs/go/bin/ks -ldflags="-X main.version=dev-2018-12-17T13:35:57+0800 -X main.apimachineryVersion=kubernetes-1.10.4 -X generator.revision=7c76c9a36caccb5261c05c5152919b6ae1badcc0  "  ./cmd/ks
# github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/printer
vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/printer/printer.go:185:8: undefined: strings.Builder
vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/printer/printer.go:225:8: undefined: strings.Builder
vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/printer/printer.go:748:11: undefined: strings.Builder
$  go version
go version go1.9.4 linux/amd64
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
follow [doc](https://github.com/ksonnet/ksonnet/blob/master/docs/build-install.md)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by sh0rez** [comment]
Please retry with a recent go version (1.11), works for me
