### ISSUE TITLE
https://ksonnet.io is using an expired TLS certificate

### ISSUE THREAD

**Issue by programmablemike** [ksonnet/ksonnet#927]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**What happened**:
The TLS certificate for https://ksonnet.io expired on September 3, 2019

Navigating to the site in Firefox (or any other browser) prompts with a message about the site being insecure.

**What you expected to happen**:
The site should load without a message saying the site is insecure. In Firefox, the domain name in address bar should be green with a shackled lock icon.

**How to reproduce it (as minimally and precisely as possible)**:
Go to https://ksonnet.io in any browser and you should get a certificate validation error.

**Anything else we need to know?**:

**Environment**:
- ksonnet version (use `ks version`):
- Kubernetes version (use `kubectl version`):

**Comment by matthewoestreich** [comment]
@programmablemike looks like this project has been abandoned, and they don't care if their cert is expired.. (see the [first paragraph](https://github.com/ksonnet/ksonnet#ksonnet) from here)

**Comment by programmablemike** [comment]
@oze4 Thanks for pointing that out. Closing the ticket.
